module(name = "mabel_examples_android_kotlin")

bazel_dep(name = "mabel", version = "0.0.0")
bazel_dep(name = "rules_java", version = "9.3.0")
bazel_dep(name = "rules_android", version = "0.7.2")
bazel_dep(name = "rules_kotlin", version = "2.3.20")

# Android SDK and tools
remote_android_extensions = use_extension(
    "@rules_android//bzlmod_extensions:android_extensions.bzl",
    "remote_android_tools_extensions",
)
use_repo(remote_android_extensions, "android_tools")

android_sdk_repository_extension = use_extension(
    "@rules_android//rules/android_sdk_repository:rule.bzl",
    "android_sdk_repository_extension",
)
use_repo(android_sdk_repository_extension, "androidsdk")

register_toolchains("@androidsdk//:sdk-toolchain", "@androidsdk//:all")

# Maven dependencies
mabel = use_extension("@mabel//rules:extensions.bzl", "mabel")
mabel.install(
    aliases_repo = "mvn_android_kotlin",
    lockfile = "//program:maven_install.json",
)
use_repo(mabel, "mvn_android_kotlin")
