workspace(name = "mabel_examples_android")

### http_archive
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_java",
    sha256 = "bcfabfb407cb0c8820141310faa102f7fb92cc806b0f0e26a625196101b0b57e",
    urls = [
        "https://github.com/bazelbuild/rules_java/releases/download/5.5.0/rules_java-5.5.0.tar.gz",
    ],
)

load("@rules_java//java:repositories.bzl", "rules_java_dependencies", "rules_java_toolchains")

rules_java_dependencies()

rules_java_toolchains()

# Or a later commit
RULES_ANDROID_COMMIT = "b5f00721a03801b5467ac2e8f39fc60bb200992a"

RULES_ANDROID_SHA = "25fd56b68cf5e41c8995a8951d1d5f1acb74c7b310ee55b01c005d5dc0833a2c"

http_archive(
    name = "build_bazel_rules_android",
    sha256 = RULES_ANDROID_SHA,
    strip_prefix = "rules_android-%s" % RULES_ANDROID_COMMIT,
    url = "https://github.com/bazelbuild/rules_android/archive/%s.zip" % RULES_ANDROID_COMMIT,
)

load("@build_bazel_rules_android//:prereqs.bzl", "rules_android_prereqs")

rules_android_prereqs()

load("@build_bazel_rules_android//:defs.bzl", "rules_android_workspace")

rules_android_workspace()

register_toolchains(
    "@build_bazel_rules_android//toolchains/android:android_default_toolchain",
    "@build_bazel_rules_android//toolchains/android_sdk:android_sdk_tools",
)

# Of course, this `local_repository` should be `http_archive` in your project (read the README.md file at the root)
local_repository(
    name = "mabel",
    path = "../../",
)

load("@mabel//:init_rules.bzl", "init_mabel_rules")

init_mabel_rules()

load("//program/main_deps:dependencies.bzl", generate_example_workspace_rules = "generate_workspace_rules")

generate_example_workspace_rules()

### Kotlin rules
rules_kotlin_version = "1.7.1"

rules_kotlin_sha = "fd92a98bd8a8f0e1cdcb490b93f5acef1f1727ed992571232d33de42395ca9b3"

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = rules_kotlin_sha,
    urls = ["https://github.com/bazelbuild/rules_kotlin/releases/download/v%s/rules_kotlin_release.tgz" % rules_kotlin_version],
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")

kotlin_repositories()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")

kt_register_toolchains()
