# Auto-generated by https://github.com/menny/bazel-mvn-deps


# Loading a drop-in replacement for native.http_file
load('@bazel_tools//tools/build_defs/repo:http.bzl', 'http_file')

# Repository rules macro to be run in the WORKSPACE file.
def generate_workspace_rules():
    # from com.google.auto.value:auto-value-annotations:1.6.3
    http_file(name = 'apt___com_google_auto_value__auto_value_annotations__1_6_3',
        urls = ['https://repo1.maven.org/maven2/com/google/auto/value/auto-value-annotations/1.6.3/auto-value-annotations-1.6.3.jar'],
        downloaded_file_path = 'auto-value-annotations-1.6.3.jar',
    )

    # from com.google.auto.value:auto-value:1.6.3
    http_file(name = 'apt___com_google_auto_value__auto_value__1_6_3',
        urls = ['https://repo1.maven.org/maven2/com/google/auto/value/auto-value/1.6.3/auto-value-1.6.3.jar'],
        downloaded_file_path = 'auto-value-1.6.3.jar',
    )

    # from com.google.code.findbugs:jsr305:1.3.9
    http_file(name = 'apt___com_google_code_findbugs__jsr305__1_3_9',
        urls = ['https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar'],
        downloaded_file_path = 'jsr305-1.3.9.jar',
    )

    # from com.google.dagger:dagger-compiler:2.19
    http_file(name = 'apt___com_google_dagger__dagger_compiler__2_19',
        urls = ['https://repo1.maven.org/maven2/com/google/dagger/dagger-compiler/2.19/dagger-compiler-2.19.jar'],
        downloaded_file_path = 'dagger-compiler-2.19.jar',
    )

    # from com.google.dagger:dagger-producers:2.19
    http_file(name = 'apt___com_google_dagger__dagger_producers__2_19',
        urls = ['https://repo1.maven.org/maven2/com/google/dagger/dagger-producers/2.19/dagger-producers-2.19.jar'],
        downloaded_file_path = 'dagger-producers-2.19.jar',
    )

    # from com.google.dagger:dagger-spi:2.19
    http_file(name = 'apt___com_google_dagger__dagger_spi__2_19',
        urls = ['https://repo1.maven.org/maven2/com/google/dagger/dagger-spi/2.19/dagger-spi-2.19.jar'],
        downloaded_file_path = 'dagger-spi-2.19.jar',
    )

    # from com.google.dagger:dagger:2.19
    http_file(name = 'apt___com_google_dagger__dagger__2_19',
        urls = ['https://repo1.maven.org/maven2/com/google/dagger/dagger/2.19/dagger-2.19.jar'],
        downloaded_file_path = 'dagger-2.19.jar',
    )

    # from com.google.errorprone:error_prone_annotations:2.1.3
    http_file(name = 'apt___com_google_errorprone__error_prone_annotations__2_1_3',
        urls = ['https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'],
        downloaded_file_path = 'error_prone_annotations-2.1.3.jar',
    )

    # from com.google.errorprone:javac-shaded:9-dev-r4023-3
    http_file(name = 'apt___com_google_errorprone__javac_shaded__9_dev_r4023_3',
        urls = ['https://repo1.maven.org/maven2/com/google/errorprone/javac-shaded/9-dev-r4023-3/javac-shaded-9-dev-r4023-3.jar'],
        downloaded_file_path = 'javac-shaded-9-dev-r4023-3.jar',
    )

    # from com.google.googlejavaformat:google-java-format:1.5
    http_file(name = 'apt___com_google_googlejavaformat__google_java_format__1_5',
        urls = ['https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.5/google-java-format-1.5.jar'],
        downloaded_file_path = 'google-java-format-1.5.jar',
    )

    # from com.google.guava:guava:25.0-jre
    http_file(name = 'apt___com_google_guava__guava__25_0_jre',
        urls = ['https://repo1.maven.org/maven2/com/google/guava/guava/25.0-jre/guava-25.0-jre.jar'],
        downloaded_file_path = 'guava-25.0-jre.jar',
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    http_file(name = 'apt___com_google_j2objc__j2objc_annotations__1_1',
        urls = ['https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar'],
        downloaded_file_path = 'j2objc-annotations-1.1.jar',
    )

    # from com.squareup:javapoet:1.11.1
    http_file(name = 'apt___com_squareup__javapoet__1_11_1',
        urls = ['https://repo1.maven.org/maven2/com/squareup/javapoet/1.11.1/javapoet-1.11.1.jar'],
        downloaded_file_path = 'javapoet-1.11.1.jar',
    )

    # from javax.annotation:jsr250-api:1.0
    http_file(name = 'apt___javax_annotation__jsr250_api__1_0',
        urls = ['https://repo1.maven.org/maven2/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar'],
        downloaded_file_path = 'jsr250-api-1.0.jar',
    )

    # from javax.inject:javax.inject:1
    http_file(name = 'apt___javax_inject__javax_inject__1',
        urls = ['https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar'],
        downloaded_file_path = 'javax.inject-1.jar',
    )

    # from org.checkerframework:checker-compat-qual:2.5.3
    http_file(name = 'apt___org_checkerframework__checker_compat_qual__2_5_3',
        urls = ['https://repo1.maven.org/maven2/org/checkerframework/checker-compat-qual/2.5.3/checker-compat-qual-2.5.3.jar'],
        downloaded_file_path = 'checker-compat-qual-2.5.3.jar',
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.14
    http_file(name = 'apt___org_codehaus_mojo__animal_sniffer_annotations__1_14',
        urls = ['https://repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar'],
        downloaded_file_path = 'animal-sniffer-annotations-1.14.jar',
    )


# Transitive rules macro to be run in the BUILD.bazel file.
# If you use kt_* rules, you MUST provide the correct rule implementation when call this macro, if you decide
# not to provide those implementations we'll try to use java_* rules.

# This is a help macro to handle Kotlin rules.
def kotlin_jar_support(name, deps, exports, runtime_deps, jar, kt_jvm_import=None, kt_jvm_library=None):
    #In case the developer did not provide a kt_* impl, we'll try to use java_*, should work
    if kt_jvm_import == None:
        native.java_import(name = name,
            jars = [jar],
            deps = deps,
            exports = exports,
            runtime_deps = runtime_deps,
        )
    else:
        kt_jvm_import(name = '{}_kotlin_jar'.format(name),
            jars = [jar],
        )
        kt_jvm_library(name = name,
            deps = deps + [':{}_kotlin_jar'.format(name)],
            exports = exports + [':{}_kotlin_jar'.format(name)],
            runtime_deps = runtime_deps,
        )

def generate_transitive_dependency_targets(kt_jvm_import=None, kt_jvm_library=None):
    # from com.google.auto.value:auto-value-annotations:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value_annotations',
        actual = ':apt___com_google_auto_value__auto_value_annotations__1_6_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value-annotations:1.6.3
    native.java_import(name = 'apt___com_google_auto_value__auto_value_annotations__1_6_3',
        jars = ['@apt___com_google_auto_value__auto_value_annotations__1_6_3//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_import(name = 'apt___com_google_auto_value__auto_value__1_6_3',
        jars = ['@apt___com_google_auto_value__auto_value__1_6_3//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_0',
        processor_class = 'com.google.auto.value.extension.memoized.processor.MemoizedValidator',
        generates_api = 1,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_1',
        processor_class = 'com.google.auto.value.processor.AutoAnnotationProcessor',
        generates_api = 1,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_2',
        processor_class = 'com.google.auto.value.processor.AutoOneOfProcessor',
        generates_api = 1,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_3',
        processor_class = 'com.google.auto.value.processor.AutoValueBuilderProcessor',
        generates_api = 1,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_4',
        processor_class = 'com.google.auto.value.processor.AutoValueProcessor',
        generates_api = 1,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_library(name = 'apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_all',
        exported_plugins = [
            ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_0',
            ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_1',
            ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_2',
            ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_3',
            ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_4',
        ],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_0',
        processor_class = 'com.google.auto.value.extension.memoized.processor.MemoizedValidator',
        generates_api = 0,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_1',
        processor_class = 'com.google.auto.value.processor.AutoAnnotationProcessor',
        generates_api = 0,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_2',
        processor_class = 'com.google.auto.value.processor.AutoOneOfProcessor',
        generates_api = 0,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_3',
        processor_class = 'com.google.auto.value.processor.AutoValueBuilderProcessor',
        generates_api = 0,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_plugin(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_4',
        processor_class = 'com.google.auto.value.processor.AutoValueProcessor',
        generates_api = 0,
        deps = [':apt___com_google_auto_value__auto_value__1_6_3'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.java_library(name = 'apt___com_google_auto_value__auto_value__1_6_3___processor_class_all',
        exported_plugins = [
            ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_0',
            ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_1',
            ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_2',
            ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_3',
            ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_4',
        ],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_0',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_0',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_1',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_1',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_2',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_2',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_3',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_4',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_4',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___generates_api___processor_class_all',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___generates_api___processor_class_all',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_0',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_0',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_1',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_1',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_2',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_2',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_3',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_4',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_4',
        visibility = ['//visibility:public'],
    )

    # from com.google.auto.value:auto-value:1.6.3
    native.alias(name = 'apt___com_google_auto_value__auto_value___processor_class_all',
        actual = ':apt___com_google_auto_value__auto_value__1_6_3___processor_class_all',
        visibility = ['//visibility:public'],
    )

    # from com.google.code.findbugs:jsr305:1.3.9
    native.alias(name = 'apt___com_google_code_findbugs__jsr305',
        actual = ':apt___com_google_code_findbugs__jsr305__1_3_9',
        visibility = ['//visibility:public'],
    )

    # from com.google.code.findbugs:jsr305:1.3.9
    native.java_import(name = 'apt___com_google_code_findbugs__jsr305__1_3_9',
        jars = ['@apt___com_google_code_findbugs__jsr305__1_3_9//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_compiler',
        actual = ':apt___com_google_dagger__dagger_compiler__2_19',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.java_import(name = 'apt___com_google_dagger__dagger_compiler__2_19',
        jars = ['@apt___com_google_dagger__dagger_compiler__2_19//file'],
        licenses = ['notice'],
        deps = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_dagger__dagger_spi',
            ':apt___com_google_googlejavaformat__google_java_format',
            ':apt___com_google_guava__guava',
            ':apt___com_squareup__javapoet',
            ':apt___javax_annotation__jsr250_api',
            ':apt___javax_inject__javax_inject',
        ],
        exports = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_dagger__dagger_spi',
            ':apt___com_google_googlejavaformat__google_java_format',
            ':apt___com_google_guava__guava',
            ':apt___com_squareup__javapoet',
            ':apt___javax_annotation__jsr250_api',
            ':apt___javax_inject__javax_inject',
        ],
        runtime_deps = [],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.java_plugin(name = 'apt___com_google_dagger__dagger_compiler__2_19___generates_api___processor_class_0',
        processor_class = 'dagger.internal.codegen.ComponentProcessor',
        generates_api = 1,
        deps = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_compiler__2_19',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_dagger__dagger_spi',
            ':apt___com_google_googlejavaformat__google_java_format',
            ':apt___com_google_guava__guava',
            ':apt___com_squareup__javapoet',
            ':apt___javax_annotation__jsr250_api',
            ':apt___javax_inject__javax_inject',
        ],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.java_library(name = 'apt___com_google_dagger__dagger_compiler__2_19___generates_api___processor_class_all',
        exported_plugins = [':apt___com_google_dagger__dagger_compiler__2_19___generates_api___processor_class_0'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.java_plugin(name = 'apt___com_google_dagger__dagger_compiler__2_19___processor_class_0',
        processor_class = 'dagger.internal.codegen.ComponentProcessor',
        generates_api = 0,
        deps = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_compiler__2_19',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_dagger__dagger_spi',
            ':apt___com_google_googlejavaformat__google_java_format',
            ':apt___com_google_guava__guava',
            ':apt___com_squareup__javapoet',
            ':apt___javax_annotation__jsr250_api',
            ':apt___javax_inject__javax_inject',
        ],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.java_library(name = 'apt___com_google_dagger__dagger_compiler__2_19___processor_class_all',
        exported_plugins = [':apt___com_google_dagger__dagger_compiler__2_19___processor_class_0'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_compiler___generates_api___processor_class_0',
        actual = ':apt___com_google_dagger__dagger_compiler__2_19___generates_api___processor_class_0',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_compiler___generates_api___processor_class_all',
        actual = ':apt___com_google_dagger__dagger_compiler__2_19___generates_api___processor_class_all',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_compiler___processor_class_0',
        actual = ':apt___com_google_dagger__dagger_compiler__2_19___processor_class_0',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-compiler:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_compiler___processor_class_all',
        actual = ':apt___com_google_dagger__dagger_compiler__2_19___processor_class_all',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-producers:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_producers',
        actual = ':apt___com_google_dagger__dagger_producers__2_19',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-producers:2.19
    native.java_import(name = 'apt___com_google_dagger__dagger_producers__2_19',
        jars = ['@apt___com_google_dagger__dagger_producers__2_19//file'],
        licenses = ['notice'],
        deps = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_guava__guava',
            ':apt___javax_inject__javax_inject',
            ':apt___org_checkerframework__checker_compat_qual',
        ],
        exports = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_guava__guava',
            ':apt___javax_inject__javax_inject',
            ':apt___org_checkerframework__checker_compat_qual',
        ],
        runtime_deps = [],
    )

    # from com.google.dagger:dagger-spi:2.19
    native.alias(name = 'apt___com_google_dagger__dagger_spi',
        actual = ':apt___com_google_dagger__dagger_spi__2_19',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger-spi:2.19
    native.java_import(name = 'apt___com_google_dagger__dagger_spi__2_19',
        jars = ['@apt___com_google_dagger__dagger_spi__2_19//file'],
        licenses = ['notice'],
        deps = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_guava__guava',
            ':apt___javax_inject__javax_inject',
        ],
        exports = [
            ':apt___com_google_dagger__dagger',
            ':apt___com_google_dagger__dagger_producers',
            ':apt___com_google_guava__guava',
            ':apt___javax_inject__javax_inject',
        ],
        runtime_deps = [],
    )

    # from com.google.dagger:dagger:2.19
    native.alias(name = 'apt___com_google_dagger__dagger',
        actual = ':apt___com_google_dagger__dagger__2_19',
        visibility = ['//visibility:public'],
    )

    # from com.google.dagger:dagger:2.19
    native.java_import(name = 'apt___com_google_dagger__dagger__2_19',
        jars = ['@apt___com_google_dagger__dagger__2_19//file'],
        licenses = ['notice'],
        deps = [':apt___javax_inject__javax_inject'],
        exports = [':apt___javax_inject__javax_inject'],
        runtime_deps = [],
    )

    # from com.google.errorprone:error_prone_annotations:2.1.3
    native.alias(name = 'apt___com_google_errorprone__error_prone_annotations',
        actual = ':apt___com_google_errorprone__error_prone_annotations__2_1_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.errorprone:error_prone_annotations:2.1.3
    native.java_import(name = 'apt___com_google_errorprone__error_prone_annotations__2_1_3',
        jars = ['@apt___com_google_errorprone__error_prone_annotations__2_1_3//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.errorprone:javac-shaded:9-dev-r4023-3
    native.alias(name = 'apt___com_google_errorprone__javac_shaded',
        actual = ':apt___com_google_errorprone__javac_shaded__9_dev_r4023_3',
        visibility = ['//visibility:public'],
    )

    # from com.google.errorprone:javac-shaded:9-dev-r4023-3
    native.java_import(name = 'apt___com_google_errorprone__javac_shaded__9_dev_r4023_3',
        jars = ['@apt___com_google_errorprone__javac_shaded__9_dev_r4023_3//file'],
        licenses = ['restricted'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.googlejavaformat:google-java-format:1.5
    native.alias(name = 'apt___com_google_googlejavaformat__google_java_format',
        actual = ':apt___com_google_googlejavaformat__google_java_format__1_5',
        visibility = ['//visibility:public'],
    )

    # from com.google.googlejavaformat:google-java-format:1.5
    native.java_import(name = 'apt___com_google_googlejavaformat__google_java_format__1_5',
        jars = ['@apt___com_google_googlejavaformat__google_java_format__1_5//file'],
        licenses = ['notice'],
        deps = [
            ':apt___com_google_errorprone__javac_shaded',
            ':apt___com_google_guava__guava',
        ],
        exports = [
            ':apt___com_google_errorprone__javac_shaded',
            ':apt___com_google_guava__guava',
        ],
        runtime_deps = [],
    )

    # from com.google.guava:guava:25.0-jre
    native.alias(name = 'apt___com_google_guava__guava',
        actual = ':apt___com_google_guava__guava__25_0_jre',
        visibility = ['//visibility:public'],
    )

    # from com.google.guava:guava:25.0-jre
    native.java_import(name = 'apt___com_google_guava__guava__25_0_jre',
        jars = ['@apt___com_google_guava__guava__25_0_jre//file'],
        licenses = ['notice'],
        deps = [
            ':apt___com_google_code_findbugs__jsr305',
            ':apt___com_google_errorprone__error_prone_annotations',
            ':apt___com_google_j2objc__j2objc_annotations',
            ':apt___org_checkerframework__checker_compat_qual',
            ':apt___org_codehaus_mojo__animal_sniffer_annotations',
        ],
        exports = [
            ':apt___com_google_code_findbugs__jsr305',
            ':apt___com_google_errorprone__error_prone_annotations',
            ':apt___com_google_j2objc__j2objc_annotations',
            ':apt___org_checkerframework__checker_compat_qual',
            ':apt___org_codehaus_mojo__animal_sniffer_annotations',
        ],
        runtime_deps = [],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    native.alias(name = 'apt___com_google_j2objc__j2objc_annotations',
        actual = ':apt___com_google_j2objc__j2objc_annotations__1_1',
        visibility = ['//visibility:public'],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    native.java_import(name = 'apt___com_google_j2objc__j2objc_annotations__1_1',
        jars = ['@apt___com_google_j2objc__j2objc_annotations__1_1//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.squareup:javapoet:1.11.1
    native.alias(name = 'apt___com_squareup__javapoet',
        actual = ':apt___com_squareup__javapoet__1_11_1',
        visibility = ['//visibility:public'],
    )

    # from com.squareup:javapoet:1.11.1
    native.java_import(name = 'apt___com_squareup__javapoet__1_11_1',
        jars = ['@apt___com_squareup__javapoet__1_11_1//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from javax.annotation:jsr250-api:1.0
    native.alias(name = 'apt___javax_annotation__jsr250_api',
        actual = ':apt___javax_annotation__jsr250_api__1_0',
        visibility = ['//visibility:public'],
    )

    # from javax.annotation:jsr250-api:1.0
    native.java_import(name = 'apt___javax_annotation__jsr250_api__1_0',
        jars = ['@apt___javax_annotation__jsr250_api__1_0//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from javax.inject:javax.inject:1
    native.alias(name = 'apt___javax_inject__javax_inject',
        actual = ':apt___javax_inject__javax_inject__1',
        visibility = ['//visibility:public'],
    )

    # from javax.inject:javax.inject:1
    native.java_import(name = 'apt___javax_inject__javax_inject__1',
        jars = ['@apt___javax_inject__javax_inject__1//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.checkerframework:checker-compat-qual:2.5.3
    native.alias(name = 'apt___org_checkerframework__checker_compat_qual',
        actual = ':apt___org_checkerframework__checker_compat_qual__2_5_3',
        visibility = ['//visibility:public'],
    )

    # from org.checkerframework:checker-compat-qual:2.5.3
    native.java_import(name = 'apt___org_checkerframework__checker_compat_qual__2_5_3',
        jars = ['@apt___org_checkerframework__checker_compat_qual__2_5_3//file'],
        licenses = [
            'notice',
            'restricted',
        ],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.14
    native.alias(name = 'apt___org_codehaus_mojo__animal_sniffer_annotations',
        actual = ':apt___org_codehaus_mojo__animal_sniffer_annotations__1_14',
        visibility = ['//visibility:public'],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.14
    native.java_import(name = 'apt___org_codehaus_mojo__animal_sniffer_annotations__1_14',
        jars = ['@apt___org_codehaus_mojo__animal_sniffer_annotations__1_14//file'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )


