"""
Bzlmod module extension for mabel Maven dependency management.

This extension reads a lockfile (generated by running mabel_rule) and creates
repository rules for all Maven artifacts without needing to re-resolve dependencies.
"""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def _maven_install_impl(module_ctx):
    """
    Module extension implementation that reads the lockfile and creates repos.

    This function:
    1. Reads the JSON lockfile specified by the user
    2. Parses the artifact metadata
    3. Creates http_file repository rules for each Maven artifact
    """

    # Collect all install tags from modules that use this extension
    for mod in module_ctx.modules:
        for install in mod.tags.install:
            lockfile_path = install.lockfile

            # Read the lockfile
            lockfile_content = module_ctx.read(lockfile_path)
            lockfile = json.decode(lockfile_content)

            # Validate lockfile version
            if lockfile.get("version") != "1.0":
                fail("Unsupported lockfile version: {}".format(lockfile.get("version")))

            # Create repository rules for each artifact
            artifacts = lockfile.get("artifacts", {})
            for maven_coordinate, artifact_info in artifacts.items():
                repo_name = artifact_info.get("repo_name")
                url = artifact_info.get("url")
                sha256 = artifact_info.get("sha256")

                if not repo_name or not url:
                    fail("Invalid artifact entry for {}: missing repo_name or url".format(maven_coordinate))

                # Create http_file repository rule for the main artifact
                http_file_attrs = {
                    "urls": [url],
                    "downloaded_file_path": url.split("/")[-1],  # Extract filename from URL
                }

                # Add sha256 if available (not present for SNAPSHOTs)
                if sha256:
                    http_file_attrs["sha256"] = sha256

                http_file(
                    name = repo_name,
                    **http_file_attrs
                )

                # Create http_file for sources if available
                sources = artifact_info.get("sources")
                if sources and sources.get("url"):
                    sources_repo_name = repo_name + "__sources"
                    sources_attrs = {
                        "urls": [sources["url"]],
                        "downloaded_file_path": sources["url"].split("/")[-1],
                    }
                    if sources.get("sha256"):
                        sources_attrs["sha256"] = sources["sha256"]

                    http_file(
                        name = sources_repo_name,
                        **sources_attrs
                    )

# Define the tag class for the install operation
_install_tag = tag_class(
    attrs = {
        "lockfile": attr.label(
            doc = "Label pointing to the Maven lockfile (e.g., '//resolver:maven_install.json')",
            mandatory = True,
        ),
    },
)

# Define the module extension
maven = module_extension(
    implementation = _maven_install_impl,
    tag_classes = {
        "install": _install_tag,
    },
)
