load("//tools:linters.bzl", "checkstyle_test")

checkstyle_test(
    name = "checkstyle",
    srcs = [
        "//resolver:api_lib",
        "//resolver:api_model",
        "//resolver:graph_resolver_lib",
        "//resolver:impl_lib",
        "//resolver:merger",
        "//resolver:merger_bin",
        "//resolver:migration_tooling_graph_resolver",
        "//resolver:resolver_bin",
        "//resolver:serialization",
        "//resolver:test_utils",
        "//resolver:timing_lib",
    ],
)
