load("@rules_java//java:defs.bzl", "java_binary", "java_library", "java_plugin")
load("//rules:mabel.bzl", "artifact", "mabel_rule")

package(default_visibility = ["//visibility:public"])

# AutoValue annotation processor
java_plugin(
    name = "autovalue_plugin",
    processor_class = "com.google.auto.value.processor.AutoValueProcessor",
    deps = ["@mvn//com/google/auto/value/auto-value"],
)

_AETHER_VERSION = "1.1.0"

_APACHE_MAVEN_VERSION = "3.8.1"

mabel_rule(
    name = "main_deps",
    default_exports_generation = "requested_deps",
    default_target_type = "naive",
    lockfile_path = "resolver/maven_install.json",
    maven_deps = [
        artifact(
            "com.google.guava:guava:27.0.1-jre",
            type = "jar",
        ),
        artifact(
            "org.apache.commons:commons-lang3:jar:3.8.1",
        ),
        artifact(
            "com.google.code.findbugs:jsr305:3.0.2",
        ),

        #command-line arguments parsing
        artifact(
            "com.beust:jcommander:1.72",
        ),

        #POM management
        artifact(
            "org.eclipse.aether:aether-api:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-spi:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-impl:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-util:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-transport-http:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-transport-classpath:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-transport-wagon:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-transport-file:" + _AETHER_VERSION,
        ),
        artifact(
            "org.eclipse.aether:aether-connector-basic:" + _AETHER_VERSION,
        ),
        artifact(
            "org.apache.maven:maven-aether-provider:3.3.9",
        ),
        artifact(
            "org.apache.maven:maven-model:" + _APACHE_MAVEN_VERSION,
        ),
        artifact(
            "org.apache.maven:maven-model-builder:" + _APACHE_MAVEN_VERSION,
        ),
        artifact(
            "org.apache.maven:maven-repository-metadata:" + _APACHE_MAVEN_VERSION,
        ),
        artifact(
            "org.apache.maven:maven-artifact:" + _APACHE_MAVEN_VERSION,
        ),
        artifact(
            "org.apache.httpcomponents:httpclient:4.5.13",
        ),
        artifact(
            "org.codehaus.plexus:plexus-interpolation:1.26",
        ),
        artifact(
            "org.codehaus.plexus:plexus-utils:3.3.0",
        ),

        #model classes
        artifact(
            "com.google.auto.value:auto-value-annotations:1.7",
        ),
        artifact(
            "com.google.auto.value:auto-value:1.7",
            type = "processor",
        ),
        #for creating and reading json
        artifact(
            "com.google.code.gson:gson:2.8.5",
        ),

        #logging - nop
        artifact(
            "org.slf4j:slf4j-nop:1.7.25",
        ),

        #testing
        artifact(
            "junit:junit:4.12",
            test_only = True,
        ),
        artifact(
            "org.mockito:mockito-core:2.23.4",
            test_only = True,
        ),
    ],
    public_targets_category = "requested_deps",
)

java_library(
    name = "api_model",
    srcs = glob(["src/main/java/net/evendanan/bazel/mvn/api/model/*.java"]),
    plugins = [":autovalue_plugin"],
    deps = [
        "@mvn//com/google/auto/value/auto-value-annotations",
    ],
)

java_library(
    name = "serialization",
    srcs = glob(["src/main/java/net/evendanan/bazel/mvn/api/serialization/*.java"]),
    deps = [
        ":api_model",
        "@mvn//com/google/code/gson/gson",
    ],
)

java_library(
    name = "graph_resolver_lib",
    srcs = glob(["src/main/java/com/google/devtools/bazel/workspace/maven/*.java"]),
    runtime_deps = [
        "@mvn//org/codehaus/plexus/plexus-interpolation",
        "@mvn//org/codehaus/plexus/plexus-utils",
    ],
    deps = [
        ":api_lib",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
        "@mvn//org/apache/httpcomponents/httpclient",
        "@mvn//org/apache/maven/maven-aether-provider",
        "@mvn//org/apache/maven/maven-artifact",
        "@mvn//org/apache/maven/maven-builder-support",
        "@mvn//org/apache/maven/maven-model",
        "@mvn//org/apache/maven/maven-model-builder",
        "@mvn//org/apache/maven/maven-repository-metadata",
        "@mvn//org/eclipse/aether/aether-api",
        "@mvn//org/eclipse/aether/aether-connector-basic",
        "@mvn//org/eclipse/aether/aether-impl",
        "@mvn//org/eclipse/aether/aether-spi",
        "@mvn//org/eclipse/aether/aether-transport-classpath",
        "@mvn//org/eclipse/aether/aether-transport-file",
        "@mvn//org/eclipse/aether/aether-transport-http",
        "@mvn//org/eclipse/aether/aether-transport-wagon",
        "@mvn//org/eclipse/aether/aether-util",
    ],
)

java_library(
    name = "migration_tooling_graph_resolver",
    srcs = glob(["src/main/java/com/google/devtools/bazel/workspace/maven/adapter/*.java"]),
    deps = [
        ":api_lib",
        ":graph_resolver_lib",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/maven/maven-model",
    ],
)

java_library(
    name = "timing_lib",
    srcs = glob(["src/main/java/net/evendanan/timing/*.java"]),
    runtime_deps = [],
    deps = [
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
    ],
)

java_library(
    name = "api_lib",
    srcs = glob(["src/main/java/net/evendanan/bazel/mvn/api/*.java"]),
    visibility = ["//visibility:public"],
    exports = [":api_model"],
    runtime_deps = [],
    deps = [
        ":api_model",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
    ],
)

java_library(
    name = "impl_lib",
    srcs = glob(["src/main/java/net/evendanan/bazel/mvn/impl/*.java"]),
    runtime_deps = [],
    deps = [
        ":api_lib",
        ":timing_lib",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/code/gson/gson",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
    ],
)

java_library(
    name = "merger",
    srcs = glob(["src/main/java/net/evendanan/bazel/mvn/merger/*.java"]),
    deps = [
        ":api_lib",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
    ],
)

java_binary(
    name = "resolver_bin",
    srcs = ["src/main/java/net/evendanan/bazel/mvn/Resolver.java"],
    main_class = "net.evendanan.bazel.mvn.Resolver",
    visibility = ["//visibility:public"],
    runtime_deps = ["@mvn//org/slf4j/slf4j-nop"],
    deps = [
        ":api_lib",
        ":impl_lib",
        ":migration_tooling_graph_resolver",
        ":serialization",
        ":timing_lib",
        "@mvn//com/beust/jcommander",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
        "@mvn//org/apache/maven/maven-model",
    ],
)

java_binary(
    name = "merger_bin",
    srcs = [
        "src/main/java/net/evendanan/bazel/mvn/CommandLineOptions.java",
        "src/main/java/net/evendanan/bazel/mvn/Merger.java",
    ],
    main_class = "net.evendanan.bazel.mvn.Merger",
    visibility = ["//visibility:public"],
    runtime_deps = ["@mvn//org/slf4j/slf4j-nop"],
    deps = [
        ":api_lib",
        ":impl_lib",
        ":merger",
        ":serialization",
        ":timing_lib",
        "@mvn//com/beust/jcommander",
        "@mvn//com/google/code/findbugs/jsr305",
        "@mvn//com/google/guava/guava",
        "@mvn//org/apache/commons/commons-lang3",
    ],
)
