"""
Required macros for creating repository-rules and third-party Maven dependencies.

Auto-generated by https://github.com/menny/mabel
"""

# Loading a drop-in replacement for native.http_file
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")
load("@mabel//rules/jvm_import:jvm_import.bzl", "jvm_import")

def generate_workspace_rules(name = "generate_workspace_rules"):
    """
    Repository rules macro to be run in the WORKSPACE file.

    Args:
        name: A unique name for this target. No need to specify.
    """

    # from aopalliance:aopalliance:1.0
    http_file(
        name = "aopalliance__aopalliance__1_0",
        urls = ["https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar"],
        downloaded_file_path = "aopalliance-1.0.jar",
        sha256 = "0addec670fedcd3f113c5c8091d783280d23f75e3acb841b61a9cdb079376a08",
    )

    # from com.github.stephenc.jcip:jcip-annotations:1.0-1
    http_file(
        name = "com_github_stephenc_jcip__jcip_annotations__1_0_1",
        urls = ["https://repo1.maven.org/maven2/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar"],
        downloaded_file_path = "jcip-annotations-1.0-1.jar",
        sha256 = "4fccff8382aafc589962c4edb262f6aa595e34f1e11e61057d1c6a96e8fc7323",
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    http_file(
        name = "com_google_code_findbugs__jsr305__3_0_2",
        urls = ["https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar"],
        downloaded_file_path = "jsr305-3.0.2.jar",
        sha256 = "766ad2a0783f2687962c8ad74ceecc38a28b9f72a2d085ee438b7813e928d0c7",
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    http_file(
        name = "com_google_errorprone__error_prone_annotations__2_2_0",
        urls = ["https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar"],
        downloaded_file_path = "error_prone_annotations-2.2.0.jar",
        sha256 = "6ebd22ca1b9d8ec06d41de8d64e0596981d9607b42035f9ed374f9de271a481a",
    )

    # from com.google.guava:failureaccess:1.0.1
    http_file(
        name = "com_google_guava__failureaccess__1_0_1",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"],
        downloaded_file_path = "failureaccess-1.0.1.jar",
        sha256 = "a171ee4c734dd2da837e4b16be9df4661afab72a41adaf31eb84dfdaf936ca26",
    )

    # from com.google.guava:guava:20.0
    http_file(
        name = "com_google_guava__guava__20_0",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/guava/20.0/guava-20.0.jar"],
        downloaded_file_path = "guava-20.0.jar",
        sha256 = "36a666e3b71ae7f0f0dca23654b67e086e6c93d192f60ba5dfd5519db6c288c8",
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    http_file(
        name = "com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"],
        downloaded_file_path = "listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar",
        sha256 = "b372a037d4230aa57fbeffdef30fd6123f9c0c2db85d0aced00c91b974f33f99",
    )

    # from com.google.inject:guice:4.2.3
    http_file(
        name = "com_google_inject__guice__4_2_3",
        urls = ["https://repo1.maven.org/maven2/com/google/inject/guice/4.2.3/guice-4.2.3.jar"],
        downloaded_file_path = "guice-4.2.3.jar",
        sha256 = "a21e50ffbb67e7adc5b46cf7b9e1a480f1e0f04fd4201ddb1c65da91290601af",
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    http_file(
        name = "com_google_j2objc__j2objc_annotations__1_1",
        urls = ["https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar"],
        downloaded_file_path = "j2objc-annotations-1.1.jar",
        sha256 = "2994a7eb78f2710bd3d3bfb639b2c94e219cedac0d4d084d516e78c16dddecf6",
    )

    # from com.sun.activation:jakarta.activation:1.2.1
    http_file(
        name = "com_sun_activation__jakarta_activation__1_2_1",
        urls = ["https://repo1.maven.org/maven2/com/sun/activation/jakarta.activation/1.2.1/jakarta.activation-1.2.1.jar"],
        downloaded_file_path = "jakarta.activation-1.2.1.jar",
        sha256 = "d84d4ba8b55cdb7fdcbb885e6939386367433f56f5ab8cfdc302a7c3587fa92b",
    )

    # from commons-codec:commons-codec:1.13
    http_file(
        name = "commons_codec__commons_codec__1_13",
        urls = ["https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13.jar"],
        downloaded_file_path = "commons-codec-1.13.jar",
        sha256 = "61f7a3079e92b9fdd605238d0295af5fd11ac411a0a0af48deace1f6c5ffa072",
    )

    # from commons-io:commons-io:2.5
    http_file(
        name = "commons_io__commons_io__2_5",
        urls = ["https://repo1.maven.org/maven2/commons-io/commons-io/2.5/commons-io-2.5.jar"],
        downloaded_file_path = "commons-io-2.5.jar",
        sha256 = "a10418348d234968600ccb1d988efcbbd08716e1d96936ccc1880e7d22513474",
    )

    # from commons-logging:commons-logging:1.2
    http_file(
        name = "commons_logging__commons_logging__1_2",
        urls = ["https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar"],
        downloaded_file_path = "commons-logging-1.2.jar",
        sha256 = "daddea1ea0be0f56978ab3006b8ac92834afeefbd9b7e4e6316fca57df0fa636",
    )

    # from jakarta.validation:jakarta.validation-api:2.0.2
    http_file(
        name = "jakarta_validation__jakarta_validation_api__2_0_2",
        urls = ["https://repo1.maven.org/maven2/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar"],
        downloaded_file_path = "jakarta.validation-api-2.0.2.jar",
        sha256 = "b42d42428f3d922c892a909fa043287d577c0c5b165ad9b7d568cebf87fc9ea4",
    )

    # from javax.inject:javax.inject:1
    http_file(
        name = "javax_inject__javax_inject__1",
        urls = ["https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar"],
        downloaded_file_path = "javax.inject-1.jar",
        sha256 = "91c77044a50c481636c32d916fd89c9118a72195390452c81065080f957de7ff",
    )

    # from org.apache.httpcomponents:httpclient:4.5.12
    http_file(
        name = "org_apache_httpcomponents__httpclient__4_5_12",
        urls = ["https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.12/httpclient-4.5.12.jar"],
        downloaded_file_path = "httpclient-4.5.12.jar",
        sha256 = "bc5f065aba5dd815ee559dd24d9bcb797fb102ff9cfa036f5091ebc529bd3b93",
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    http_file(
        name = "org_apache_httpcomponents__httpcore__4_4_13",
        urls = ["https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar"],
        downloaded_file_path = "httpcore-4.4.13.jar",
        sha256 = "e06e89d40943245fcfa39ec537cdbfce3762aecde8f9c597780d2b00c2b43424",
    )

    # from org.checkerframework:checker-qual:2.5.2
    http_file(
        name = "org_checkerframework__checker_qual__2_5_2",
        urls = ["https://repo1.maven.org/maven2/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar"],
        downloaded_file_path = "checker-qual-2.5.2.jar",
        sha256 = "64b02691c8b9d4e7700f8ee2e742dce7ea2c6e81e662b7522c9ee3bf568c040a",
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    http_file(
        name = "org_codehaus_mojo__animal_sniffer_annotations__1_17",
        urls = ["https://repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar"],
        downloaded_file_path = "animal-sniffer-annotations-1.17.jar",
        sha256 = "92654f493ecfec52082e76354f0ebf87648dc3d5cec2e3c3cdb947c016747a53",
    )

    # from org.jboss.logging:jboss-logging:3.3.2.Final
    http_file(
        name = "org_jboss_logging__jboss_logging__3_3_2_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar"],
        downloaded_file_path = "jboss-logging-3.3.2.Final.jar",
        sha256 = "cb914bfe888da7d9162e965ac8b0d6f28f2f32eca944a00fbbf6dd3cf1aacc13",
    )

    # from org.jboss.resteasy:resteasy-client:3.13.1.Final
    http_file(
        name = "org_jboss_resteasy__resteasy_client__3_13_1_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-client/3.13.1.Final/resteasy-client-3.13.1.Final.jar"],
        downloaded_file_path = "resteasy-client-3.13.1.Final.jar",
        sha256 = "b12177a17bedb2db3efc38ceec1dc3b7e2aa052e0b392a5a9e6a1379b5347926",
    )

    # from org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final
    http_file(
        name = "org_jboss_resteasy__resteasy_jaxrs__3_13_1_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/resteasy/resteasy-jaxrs/3.13.1.Final/resteasy-jaxrs-3.13.1.Final.jar"],
        downloaded_file_path = "resteasy-jaxrs-3.13.1.Final.jar",
        sha256 = "115adedd56f985c33f037590af7e497142172f69731086f5a455c355fcdc1da8",
    )

    # from org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final
    http_file(
        name = "org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec__2_0_1_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/spec/javax/annotation/jboss-annotations-api_1.3_spec/2.0.1.Final/jboss-annotations-api_1.3_spec-2.0.1.Final.jar"],
        downloaded_file_path = "jboss-annotations-api_1.3_spec-2.0.1.Final.jar",
        sha256 = "afc4e3b8701119c9a2ceb8cebe3fd1869a269de768d7d56e7b5051827a132368",
    )

    # from org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:2.0.1.Final
    http_file(
        name = "org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec__2_0_1_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.1_spec/2.0.1.Final/jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar"],
        downloaded_file_path = "jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar",
        sha256 = "3518db0a3980aacfdae916f0eb081d0fcefaa2076d2ba603edc779a601d2d1a4",
    )

    # from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final
    http_file(
        name = "org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec__2_0_0_Final",
        urls = ["https://repo1.maven.org/maven2/org/jboss/spec/javax/xml/bind/jboss-jaxb-api_2.3_spec/2.0.0.Final/jboss-jaxb-api_2.3_spec-2.0.0.Final.jar"],
        downloaded_file_path = "jboss-jaxb-api_2.3_spec-2.0.0.Final.jar",
        sha256 = "f73f5832acef810d4d72da3b04378b6a70b72e955fdb0315591f0115c3ee701b",
    )

    # from org.reactivestreams:reactive-streams:1.0.3
    http_file(
        name = "org_reactivestreams__reactive_streams__1_0_3",
        urls = ["https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar"],
        downloaded_file_path = "reactive-streams-1.0.3.jar",
        sha256 = "1dee0481072d19c929b623e155e14d2f6085dc011529a0a0dbefc84cf571d865",
    )

def _no_op_missing_aar_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require aar_import rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a aar_import which was not provided. Add argument aar_import when calling generate_transitive_dependency_targets."
            .format(name),
    )

def generate_transitive_dependency_targets(
        name = "generate_transitive_dependency_targets",
        java_library = native.java_library,
        java_plugin = native.java_plugin,
        jvm_import = jvm_import,
        aar_import = _no_op_missing_aar_impl):
    """
    Macro to set up the transitive rules.

    You can provide your own implementation of jvm_import, aar_import, etc. This can be used
    in cases where you need to shade (or jar_jar or jetify) your jars.

    Args:
        name: a unique name for this macro. Not needed to specify.
        java_library: rule implementation for java_library. Defaults to native.java_library.
        java_plugin: rule implementation for java_plugin. Defaults to native.java_plugin.
        jvm_import: rule implementation for jvm_import. Defaults to jvm_import.
        aar_import: rule implementation for aar_import. Required only if you have Android dependencies.
    """

    # from aopalliance:aopalliance:1.0
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    native.alias(
        name = "aopalliance__aopalliance",
        actual = ":aopalliance__aopalliance__1_0",
        visibility = ["//visibility:public"],
    )

    # from aopalliance:aopalliance:1.0
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    jvm_import(
        name = "aopalliance__aopalliance__1_0",
        jars = ["@aopalliance__aopalliance__1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Public-Domain",
            "mabel_license_name=Public Domain",
            "maven_coordinates=aopalliance:aopalliance:1.0",
        ],
        licenses = ["unencumbered"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.github.stephenc.jcip:jcip-annotations:1.0-1
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "com_github_stephenc_jcip__jcip_annotations",
        actual = ":com_github_stephenc_jcip__jcip_annotations__1_0_1",
        visibility = ["//visibility:public"],
    )

    # from com.github.stephenc.jcip:jcip-annotations:1.0-1
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "com_github_stephenc_jcip__jcip_annotations__1_0_1",
        jars = ["@com_github_stephenc_jcip__jcip_annotations__1_0_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.github.stephenc.jcip:jcip-annotations:1.0-1",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    native.alias(
        name = "com_google_code_findbugs__jsr305",
        actual = ":com_google_code_findbugs__jsr305__3_0_2",
        visibility = ["//visibility:public"],
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    jvm_import(
        name = "com_google_code_findbugs__jsr305__3_0_2",
        jars = ["@com_google_code_findbugs__jsr305__3_0_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.code.findbugs:jsr305:3.0.2",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    native.alias(
        name = "com_google_errorprone__error_prone_annotations",
        actual = ":com_google_errorprone__error_prone_annotations__2_2_0",
        visibility = ["//visibility:public"],
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    jvm_import(
        name = "com_google_errorprone__error_prone_annotations__2_2_0",
        jars = ["@com_google_errorprone__error_prone_annotations__2_2_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.errorprone:error_prone_annotations:2.2.0",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.guava:failureaccess:1.0.1
    native.alias(
        name = "com_google_guava__failureaccess",
        actual = ":com_google_guava__failureaccess__1_0_1",
        visibility = ["//visibility:public"],
    )

    # from com.google.guava:failureaccess:1.0.1
    jvm_import(
        name = "com_google_guava__failureaccess__1_0_1",
        jars = ["@com_google_guava__failureaccess__1_0_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:failureaccess:1.0.1",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.guava:guava:20.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    native.alias(
        name = "com_google_guava__guava",
        actual = ":com_google_guava__guava__20_0",
        visibility = ["//visibility:public"],
    )

    # from com.google.guava:guava:20.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    jvm_import(
        name = "com_google_guava__guava__20_0",
        jars = ["@com_google_guava__guava__20_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:guava:20.0",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    native.alias(
        name = "com_google_guava__listenablefuture",
        actual = ":com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        visibility = ["//visibility:public"],
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    jvm_import(
        name = "com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        jars = ["@com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.google.inject:guice:4.2.3
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_inject__guice",
        actual = ":com_google_inject__guice__4_2_3",
        visibility = ["//visibility:public"],
    )

    # from com.google.inject:guice:4.2.3
    # This is a root requested Maven artifact.
    jvm_import(
        name = "com_google_inject__guice__4_2_3",
        jars = ["@com_google_inject__guice__4_2_3//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.inject:guice:4.2.3",
        ],
        licenses = ["notice"],
        deps = [
            ":aopalliance__aopalliance",
            ":com_google_guava__guava",
            ":javax_inject__javax_inject",
        ],
        exports = [
            ":aopalliance__aopalliance",
            ":com_google_guava__guava",
            ":javax_inject__javax_inject",
        ],
        runtime_deps = [],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    native.alias(
        name = "com_google_j2objc__j2objc_annotations",
        actual = ":com_google_j2objc__j2objc_annotations__1_1",
        visibility = ["//visibility:public"],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    jvm_import(
        name = "com_google_j2objc__j2objc_annotations__1_1",
        jars = ["@com_google_j2objc__j2objc_annotations__1_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.j2objc:j2objc-annotations:1.1",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.sun.activation:jakarta.activation:1.2.1
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "com_sun_activation__jakarta_activation",
        actual = ":com_sun_activation__jakarta_activation__1_2_1",
        visibility = ["//visibility:public"],
    )

    # from com.sun.activation:jakarta.activation:1.2.1
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "com_sun_activation__jakarta_activation__1_2_1",
        jars = ["@com_sun_activation__jakarta_activation__1_2_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=UNKNOWN",
            "mabel_license_name=EDL 1.0",
            "mabel_license_url=http://www.eclipse.org/org/documents/edl-v10.php",
            "maven_coordinates=com.sun.activation:jakarta.activation:1.2.1",
        ],
        licenses = [],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from commons-codec:commons-codec:1.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    native.alias(
        name = "commons_codec__commons_codec",
        actual = ":commons_codec__commons_codec__1_13",
        visibility = ["//visibility:public"],
    )

    # from commons-codec:commons-codec:1.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    jvm_import(
        name = "commons_codec__commons_codec__1_13",
        jars = ["@commons_codec__commons_codec__1_13//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=commons-codec:commons-codec:1.13",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from commons-io:commons-io:2.5
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "commons_io__commons_io",
        actual = ":commons_io__commons_io__2_5",
        visibility = ["//visibility:public"],
    )

    # from commons-io:commons-io:2.5
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "commons_io__commons_io__2_5",
        jars = ["@commons_io__commons_io__2_5//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=commons-io:commons-io:2.5",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from commons-logging:commons-logging:1.2
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    native.alias(
        name = "commons_logging__commons_logging",
        actual = ":commons_logging__commons_logging__1_2",
        visibility = ["//visibility:public"],
    )

    # from commons-logging:commons-logging:1.2
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    jvm_import(
        name = "commons_logging__commons_logging__1_2",
        jars = ["@commons_logging__commons_logging__1_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=commons-logging:commons-logging:1.2",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from jakarta.validation:jakarta.validation-api:2.0.2
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "jakarta_validation__jakarta_validation_api",
        actual = ":jakarta_validation__jakarta_validation_api__2_0_2",
        visibility = ["//visibility:public"],
    )

    # from jakarta.validation:jakarta.validation-api:2.0.2
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "jakarta_validation__jakarta_validation_api__2_0_2",
        jars = ["@jakarta_validation__jakarta_validation_api__2_0_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=jakarta.validation:jakarta.validation-api:2.0.2",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from javax.inject:javax.inject:1
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    native.alias(
        name = "javax_inject__javax_inject",
        actual = ":javax_inject__javax_inject__1",
        visibility = ["//visibility:public"],
    )

    # from javax.inject:javax.inject:1
    # This is a dependency of 'com.google.inject:guice:4.2.3'.
    jvm_import(
        name = "javax_inject__javax_inject__1",
        jars = ["@javax_inject__javax_inject__1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=javax.inject:javax.inject:1",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.apache.httpcomponents:httpclient:4.5.12
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_apache_httpcomponents__httpclient",
        actual = ":org_apache_httpcomponents__httpclient__4_5_12",
        visibility = ["//visibility:public"],
    )

    # from org.apache.httpcomponents:httpclient:4.5.12
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_apache_httpcomponents__httpclient__4_5_12",
        jars = ["@org_apache_httpcomponents__httpclient__4_5_12//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.httpcomponents:httpclient:4.5.12",
        ],
        licenses = ["notice"],
        deps = [
            ":commons_codec__commons_codec",
            ":commons_logging__commons_logging",
            ":org_apache_httpcomponents__httpcore",
        ],
        exports = [],
        runtime_deps = [],
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    native.alias(
        name = "org_apache_httpcomponents__httpcore",
        actual = ":org_apache_httpcomponents__httpcore__4_4_13",
        visibility = ["//visibility:public"],
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.12'.
    jvm_import(
        name = "org_apache_httpcomponents__httpcore__4_4_13",
        jars = ["@org_apache_httpcomponents__httpcore__4_4_13//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.httpcomponents:httpcore:4.4.13",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.checkerframework:checker-qual:2.5.2
    native.alias(
        name = "org_checkerframework__checker_qual",
        actual = ":org_checkerframework__checker_qual__2_5_2",
        visibility = ["//visibility:public"],
    )

    # from org.checkerframework:checker-qual:2.5.2
    jvm_import(
        name = "org_checkerframework__checker_qual__2_5_2",
        jars = ["@org_checkerframework__checker_qual__2_5_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=The MIT License",
            "mabel_license_url=http://opensource.org/licenses/MIT",
            "maven_coordinates=org.checkerframework:checker-qual:2.5.2",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    native.alias(
        name = "org_codehaus_mojo__animal_sniffer_annotations",
        actual = ":org_codehaus_mojo__animal_sniffer_annotations__1_17",
        visibility = ["//visibility:public"],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    jvm_import(
        name = "org_codehaus_mojo__animal_sniffer_annotations__1_17",
        jars = ["@org_codehaus_mojo__animal_sniffer_annotations__1_17//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=MIT license",
            "mabel_license_url=http://www.opensource.org/licenses/mit-license.php",
            "maven_coordinates=org.codehaus.mojo:animal-sniffer-annotations:1.17",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.jboss.logging:jboss-logging:3.3.2.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_jboss_logging__jboss_logging",
        actual = ":org_jboss_logging__jboss_logging__3_3_2_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.logging:jboss-logging:3.3.2.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_jboss_logging__jboss_logging__3_3_2_Final",
        jars = ["@org_jboss_logging__jboss_logging__3_3_2_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.jboss.logging:jboss-logging:3.3.2.Final",
        ],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.jboss.resteasy:resteasy-client:3.13.1.Final
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_jboss_resteasy__resteasy_client",
        actual = ":org_jboss_resteasy__resteasy_client__3_13_1_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.resteasy:resteasy-client:3.13.1.Final
    # This is a root requested Maven artifact.
    jvm_import(
        name = "org_jboss_resteasy__resteasy_client__3_13_1_Final",
        jars = ["@org_jboss_resteasy__resteasy_client__3_13_1_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License 2.0",
            "mabel_license_url=https://repository.jboss.org/licenses/apache-2.0.txt",
            "maven_coordinates=org.jboss.resteasy:resteasy-client:3.13.1.Final",
        ],
        licenses = ["notice"],
        deps = [
            ":commons_codec__commons_codec",
            ":commons_io__commons_io",
            ":org_apache_httpcomponents__httpclient",
            ":org_jboss_logging__jboss_logging",
            ":org_jboss_resteasy__resteasy_jaxrs",
            ":org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec",
        ],
        exports = [
            ":commons_codec__commons_codec",
            ":commons_io__commons_io",
            ":org_apache_httpcomponents__httpclient",
            ":org_jboss_logging__jboss_logging",
            ":org_jboss_resteasy__resteasy_jaxrs",
            ":org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec",
        ],
        runtime_deps = [],
    )

    # from org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    native.alias(
        name = "org_jboss_resteasy__resteasy_jaxrs",
        actual = ":org_jboss_resteasy__resteasy_jaxrs__3_13_1_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    jvm_import(
        name = "org_jboss_resteasy__resteasy_jaxrs__3_13_1_Final",
        jars = ["@org_jboss_resteasy__resteasy_jaxrs__3_13_1_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License 2.0",
            "mabel_license_url=https://repository.jboss.org/licenses/apache-2.0.txt",
            "maven_coordinates=org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final",
        ],
        licenses = ["notice"],
        deps = [
            ":com_github_stephenc_jcip__jcip_annotations",
            ":com_sun_activation__jakarta_activation",
            ":commons_io__commons_io",
            ":jakarta_validation__jakarta_validation_api",
            ":org_apache_httpcomponents__httpclient",
            ":org_jboss_logging__jboss_logging",
            ":org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec",
            ":org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec",
            ":org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec",
            ":org_reactivestreams__reactive_streams",
        ],
        exports = [],
        runtime_deps = [],
    )

    # from org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec",
        actual = ":org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec__2_0_1_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec__2_0_1_Final",
        jars = ["@org_jboss_spec_javax_annotation__jboss_annotations_api_1_3_spec__2_0_1_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=GPL",
            "mabel_license_detected_type=UNKNOWN",
            "mabel_license_name=EPL 2.0",
            "mabel_license_name=GPL2 w/ CPE",
            "mabel_license_url=http://www.eclipse.org/legal/epl-2.0",
            "mabel_license_url=https://www.gnu.org/software/classpath/license.html",
            "maven_coordinates=org.jboss.spec.javax.annotation:jboss-annotations-api_1.3_spec:2.0.1.Final",
        ],
        licenses = ["restricted"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:2.0.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec",
        actual = ":org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec__2_0_1_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:2.0.1.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-client:3.13.1.Final'.
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec__2_0_1_Final",
        jars = ["@org_jboss_spec_javax_ws_rs__jboss_jaxrs_api_2_1_spec__2_0_1_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=GPL",
            "mabel_license_detected_type=UNKNOWN",
            "mabel_license_name=EPL 2.0",
            "mabel_license_name=GPL2 w/ CPE",
            "mabel_license_url=http://www.eclipse.org/legal/epl-2.0",
            "mabel_license_url=https://www.gnu.org/software/classpath/license.html",
            "maven_coordinates=org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:2.0.1.Final",
        ],
        licenses = ["restricted"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec",
        actual = ":org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec__2_0_0_Final",
        visibility = ["//visibility:public"],
    )

    # from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec__2_0_0_Final",
        jars = ["@org_jboss_spec_javax_xml_bind__jboss_jaxb_api_2_3_spec__2_0_0_Final//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=UNKNOWN",
            "mabel_license_name=Eclipse Distribution License - v 1.0",
            "mabel_license_url=http://www.eclipse.org/org/documents/edl-v10.php",
            "maven_coordinates=org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:2.0.0.Final",
        ],
        licenses = [],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from org.reactivestreams:reactive-streams:1.0.3
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    native.alias(
        name = "org_reactivestreams__reactive_streams",
        actual = ":org_reactivestreams__reactive_streams__1_0_3",
        visibility = ["//visibility:public"],
    )

    # from org.reactivestreams:reactive-streams:1.0.3
    # This is a dependency of 'org.jboss.resteasy:resteasy-jaxrs:3.13.1.Final'.
    jvm_import(
        name = "org_reactivestreams__reactive_streams__1_0_3",
        jars = ["@org_reactivestreams__reactive_streams__1_0_3//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=CC0",
            "mabel_license_name=CC0",
            "mabel_license_url=http://creativecommons.org/publicdomain/zero/1.0/",
            "maven_coordinates=org.reactivestreams:reactive-streams:1.0.3",
        ],
        licenses = ["unencumbered"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )
