"""
Required macros for creating repository-rules and third-party Maven dependencies.

Auto-generated by https://github.com/menny/mabel
"""

# Loading a drop-in replacement for native.http_file
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def generate_workspace_rules(name = "generate_workspace_rules"):
    """
    Repository rules macro to be run in the WORKSPACE file.

    Args:
        name: A unique name for this target. No need to specify.
    """

    # from androidx.activity:activity:1.0.0-alpha02
    http_file(
        name = "androidx_activity__activity__1_0_0_alpha02",
        urls = ["https://maven.google.com/androidx/activity/activity/1.0.0-alpha02/activity-1.0.0-alpha02.aar"],
        downloaded_file_path = "activity-1.0.0-alpha02.aar",
    )

    # from androidx.annotation:annotation:1.0.0
    http_file(
        name = "androidx_annotation__annotation__1_0_0",
        urls = ["https://maven.google.com/androidx/annotation/annotation/1.0.0/annotation-1.0.0.jar"],
        downloaded_file_path = "annotation-1.0.0.jar",
    )

    # from androidx.appcompat:appcompat:1.0.2
    http_file(
        name = "androidx_appcompat__appcompat__1_0_2",
        urls = ["https://maven.google.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.aar"],
        downloaded_file_path = "appcompat-1.0.2.aar",
    )

    # from androidx.arch.core:core-common:2.0.0
    http_file(
        name = "androidx_arch_core__core_common__2_0_0",
        urls = ["https://maven.google.com/androidx/arch/core/core-common/2.0.0/core-common-2.0.0.jar"],
        downloaded_file_path = "core-common-2.0.0.jar",
    )

    # from androidx.arch.core:core-runtime:2.0.0
    http_file(
        name = "androidx_arch_core__core_runtime__2_0_0",
        urls = ["https://maven.google.com/androidx/arch/core/core-runtime/2.0.0/core-runtime-2.0.0.aar"],
        downloaded_file_path = "core-runtime-2.0.0.aar",
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    http_file(
        name = "androidx_asynclayoutinflater__asynclayoutinflater__1_0_0",
        urls = ["https://maven.google.com/androidx/asynclayoutinflater/asynclayoutinflater/1.0.0/asynclayoutinflater-1.0.0.aar"],
        downloaded_file_path = "asynclayoutinflater-1.0.0.aar",
    )

    # from androidx.collection:collection:1.0.0
    http_file(
        name = "androidx_collection__collection__1_0_0",
        urls = ["https://maven.google.com/androidx/collection/collection/1.0.0/collection-1.0.0.jar"],
        downloaded_file_path = "collection-1.0.0.jar",
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    http_file(
        name = "androidx_coordinatorlayout__coordinatorlayout__1_0_0",
        urls = ["https://maven.google.com/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.aar"],
        downloaded_file_path = "coordinatorlayout-1.0.0.aar",
    )

    # from androidx.core:core:1.1.0-alpha01
    http_file(
        name = "androidx_core__core__1_1_0_alpha01",
        urls = ["https://maven.google.com/androidx/core/core/1.1.0-alpha01/core-1.1.0-alpha01.aar"],
        downloaded_file_path = "core-1.1.0-alpha01.aar",
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    http_file(
        name = "androidx_cursoradapter__cursoradapter__1_0_0",
        urls = ["https://maven.google.com/androidx/cursoradapter/cursoradapter/1.0.0/cursoradapter-1.0.0.aar"],
        downloaded_file_path = "cursoradapter-1.0.0.aar",
    )

    # from androidx.customview:customview:1.0.0
    http_file(
        name = "androidx_customview__customview__1_0_0",
        urls = ["https://maven.google.com/androidx/customview/customview/1.0.0/customview-1.0.0.aar"],
        downloaded_file_path = "customview-1.0.0.aar",
    )

    # from androidx.documentfile:documentfile:1.0.0
    http_file(
        name = "androidx_documentfile__documentfile__1_0_0",
        urls = ["https://maven.google.com/androidx/documentfile/documentfile/1.0.0/documentfile-1.0.0.aar"],
        downloaded_file_path = "documentfile-1.0.0.aar",
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    http_file(
        name = "androidx_drawerlayout__drawerlayout__1_0_0",
        urls = ["https://maven.google.com/androidx/drawerlayout/drawerlayout/1.0.0/drawerlayout-1.0.0.aar"],
        downloaded_file_path = "drawerlayout-1.0.0.aar",
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    http_file(
        name = "androidx_fragment__fragment__1_1_0_alpha02",
        urls = ["https://maven.google.com/androidx/fragment/fragment/1.1.0-alpha02/fragment-1.1.0-alpha02.aar"],
        downloaded_file_path = "fragment-1.1.0-alpha02.aar",
    )

    # from androidx.interpolator:interpolator:1.0.0
    http_file(
        name = "androidx_interpolator__interpolator__1_0_0",
        urls = ["https://maven.google.com/androidx/interpolator/interpolator/1.0.0/interpolator-1.0.0.aar"],
        downloaded_file_path = "interpolator-1.0.0.aar",
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    http_file(
        name = "androidx_legacy__legacy_support_core_ui__1_0_0",
        urls = ["https://maven.google.com/androidx/legacy/legacy-support-core-ui/1.0.0/legacy-support-core-ui-1.0.0.aar"],
        downloaded_file_path = "legacy-support-core-ui-1.0.0.aar",
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    http_file(
        name = "androidx_legacy__legacy_support_core_utils__1_0_0",
        urls = ["https://maven.google.com/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.aar"],
        downloaded_file_path = "legacy-support-core-utils-1.0.0.aar",
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    http_file(
        name = "androidx_lifecycle__lifecycle_common__2_0_0",
        urls = ["https://maven.google.com/androidx/lifecycle/lifecycle-common/2.0.0/lifecycle-common-2.0.0.jar"],
        downloaded_file_path = "lifecycle-common-2.0.0.jar",
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    http_file(
        name = "androidx_lifecycle__lifecycle_livedata_core__2_0_0",
        urls = ["https://maven.google.com/androidx/lifecycle/lifecycle-livedata-core/2.0.0/lifecycle-livedata-core-2.0.0.aar"],
        downloaded_file_path = "lifecycle-livedata-core-2.0.0.aar",
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    http_file(
        name = "androidx_lifecycle__lifecycle_livedata__2_0_0",
        urls = ["https://maven.google.com/androidx/lifecycle/lifecycle-livedata/2.0.0/lifecycle-livedata-2.0.0.aar"],
        downloaded_file_path = "lifecycle-livedata-2.0.0.aar",
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    http_file(
        name = "androidx_lifecycle__lifecycle_runtime__2_0_0",
        urls = ["https://maven.google.com/androidx/lifecycle/lifecycle-runtime/2.0.0/lifecycle-runtime-2.0.0.aar"],
        downloaded_file_path = "lifecycle-runtime-2.0.0.aar",
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    http_file(
        name = "androidx_lifecycle__lifecycle_viewmodel__2_0_0",
        urls = ["https://maven.google.com/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.aar"],
        downloaded_file_path = "lifecycle-viewmodel-2.0.0.aar",
    )

    # from androidx.loader:loader:1.0.0
    http_file(
        name = "androidx_loader__loader__1_0_0",
        urls = ["https://maven.google.com/androidx/loader/loader/1.0.0/loader-1.0.0.aar"],
        downloaded_file_path = "loader-1.0.0.aar",
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    http_file(
        name = "androidx_localbroadcastmanager__localbroadcastmanager__1_0_0",
        urls = ["https://maven.google.com/androidx/localbroadcastmanager/localbroadcastmanager/1.0.0/localbroadcastmanager-1.0.0.aar"],
        downloaded_file_path = "localbroadcastmanager-1.0.0.aar",
    )

    # from androidx.print:print:1.0.0
    http_file(
        name = "androidx_print__print__1_0_0",
        urls = ["https://maven.google.com/androidx/print/print/1.0.0/print-1.0.0.aar"],
        downloaded_file_path = "print-1.0.0.aar",
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    http_file(
        name = "androidx_slidingpanelayout__slidingpanelayout__1_0_0",
        urls = ["https://maven.google.com/androidx/slidingpanelayout/slidingpanelayout/1.0.0/slidingpanelayout-1.0.0.aar"],
        downloaded_file_path = "slidingpanelayout-1.0.0.aar",
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    http_file(
        name = "androidx_swiperefreshlayout__swiperefreshlayout__1_0_0",
        urls = ["https://maven.google.com/androidx/swiperefreshlayout/swiperefreshlayout/1.0.0/swiperefreshlayout-1.0.0.aar"],
        downloaded_file_path = "swiperefreshlayout-1.0.0.aar",
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    http_file(
        name = "androidx_vectordrawable__vectordrawable_animated__1_0_0",
        urls = ["https://maven.google.com/androidx/vectordrawable/vectordrawable-animated/1.0.0/vectordrawable-animated-1.0.0.aar"],
        downloaded_file_path = "vectordrawable-animated-1.0.0.aar",
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    http_file(
        name = "androidx_vectordrawable__vectordrawable__1_0_1",
        urls = ["https://maven.google.com/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.aar"],
        downloaded_file_path = "vectordrawable-1.0.1.aar",
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    http_file(
        name = "androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01",
        urls = ["https://maven.google.com/androidx/versionedparcelable/versionedparcelable/1.1.0-alpha01/versionedparcelable-1.1.0-alpha01.aar"],
        downloaded_file_path = "versionedparcelable-1.1.0-alpha01.aar",
    )

    # from androidx.viewpager:viewpager:1.0.0
    http_file(
        name = "androidx_viewpager__viewpager__1_0_0",
        urls = ["https://maven.google.com/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.aar"],
        downloaded_file_path = "viewpager-1.0.0.aar",
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    http_file(
        name = "com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406",
        urls = ["https://jitpack.io/com/github/menny/Chauffeur/lib/90e703256785b7baf9cd37370b62b1d7d3830406/lib-90e703256785b7baf9cd37370b62b1d7d3830406.aar"],
        downloaded_file_path = "lib-90e703256785b7baf9cd37370b62b1d7d3830406.aar",
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    http_file(
        name = "com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406",
        urls = ["https://jitpack.io/com/github/menny/Chauffeur/permissions/90e703256785b7baf9cd37370b62b1d7d3830406/permissions-90e703256785b7baf9cd37370b62b1d7d3830406.aar"],
        downloaded_file_path = "permissions-90e703256785b7baf9cd37370b62b1d7d3830406.aar",
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    http_file(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2",
        urls = ["https://repo1.maven.org/maven2/com/squareup/moshi/moshi-kotlin-codegen/1.9.2/moshi-kotlin-codegen-1.9.2.jar"],
        downloaded_file_path = "moshi-kotlin-codegen-1.9.2.jar",
    )

    # from com.squareup.moshi:moshi:1.9.2
    http_file(
        name = "com_squareup_moshi__moshi__1_9_2",
        urls = ["https://repo1.maven.org/maven2/com/squareup/moshi/moshi/1.9.2/moshi-1.9.2.jar"],
        downloaded_file_path = "moshi-1.9.2.jar",
    )

    # from com.squareup.okio:okio:1.16.0
    http_file(
        name = "com_squareup_okio__okio__1_16_0",
        urls = ["https://repo1.maven.org/maven2/com/squareup/okio/okio/1.16.0/okio-1.16.0.jar"],
        downloaded_file_path = "okio-1.16.0.jar",
    )

    # from com.squareup:kotlinpoet:1.4.4
    http_file(
        name = "com_squareup__kotlinpoet__1_4_4",
        urls = ["https://repo1.maven.org/maven2/com/squareup/kotlinpoet/1.4.4/kotlinpoet-1.4.4.jar"],
        downloaded_file_path = "kotlinpoet-1.4.4.jar",
    )

    # from org.jetbrains.kotlin:kotlin-reflect:1.3.50
    http_file(
        name = "org_jetbrains_kotlin__kotlin_reflect__1_3_50",
        urls = ["https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-reflect/1.3.50/kotlin-reflect-1.3.50.jar"],
        downloaded_file_path = "kotlin-reflect-1.3.50.jar",
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
    http_file(
        name = "org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72",
        urls = ["https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.72/kotlin-stdlib-common-1.3.72.jar"],
        downloaded_file_path = "kotlin-stdlib-common-1.3.72.jar",
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
    http_file(
        name = "org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50",
        urls = ["https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.50/kotlin-stdlib-jdk7-1.3.50.jar"],
        downloaded_file_path = "kotlin-stdlib-jdk7-1.3.50.jar",
    )

    # from org.jetbrains.kotlin:kotlin-stdlib:1.3.72
    http_file(
        name = "org_jetbrains_kotlin__kotlin_stdlib__1_3_72",
        urls = ["https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.3.72/kotlin-stdlib-1.3.72.jar"],
        downloaded_file_path = "kotlin-stdlib-1.3.72.jar",
    )

    # from org.jetbrains:annotations:13.0
    http_file(
        name = "org_jetbrains__annotations__13_0",
        urls = ["https://repo1.maven.org/maven2/org/jetbrains/annotations/13.0/annotations-13.0.jar"],
        downloaded_file_path = "annotations-13.0.jar",
    )

def _no_op_missing_aar_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require aar_import rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a aar_import which was not provided. Add argument aar_import when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_jvm_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_jvm_import which was not provided. Add argument kt_jvm_import when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_jvm_lib_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_jvm_library which was not provided. Add argument kt_jvm_library when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_android_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_android_library which was not provided. Add argument kt_android_library when calling generate_transitive_dependency_targets."
            .format(name),
    )

def generate_transitive_dependency_targets(
        name = "generate_transitive_dependency_targets",
        java_library = native.java_library,
        java_plugin = native.java_plugin,
        java_import = native.java_import,
        aar_import = _no_op_missing_aar_impl,
        kt_jvm_import = _no_op_missing_kt_jvm_impl,
        kt_jvm_library = _no_op_missing_kt_jvm_lib_impl,
        kt_android_library = _no_op_missing_kt_android_impl):
    """
    Macro to set up the transitive rules.

    You can provide your own implementation of java_import, aar_import, etc. This can be used
    in cases where you need to shade (or jar_jar or jetify) your jars.

    Args:
        name: a unique name for this macro. Not needed to specify.
        java_library: rule implementation for java_library. Defaults to native.java_library.
        java_plugin: rule implementation for java_plugin. Defaults to native.java_plugin.
        java_import: rule implementation for java_import. Defaults to native.java_import.
        aar_import: rule implementation for aar_import. Required only if you have Android dependencies.
        kt_jvm_import: rule implementation for kt_jvm_import. Required only if you have Kotlin dependencies.
        kt_jvm_library: rule implementation for kt_jvm_library. Required only if you have Kotlin dependencies.
        kt_android_library: rule implementation for kt_android_library. Required only if you have Android-Kotlin dependencies.
    """

    # from androidx.activity:activity:1.0.0-alpha02
    native.alias(
        name = "androidx_activity__activity",
        actual = ":androidx_activity__activity__1_0_0_alpha02",
        visibility = ["//visibility:public"],
    )

    # from androidx.activity:activity:1.0.0-alpha02
    aar_import(
        name = "androidx_activity__activity__1_0_0_alpha02",
        aar = "@androidx_activity__activity__1_0_0_alpha02//file",
        tags = ["maven_coordinates=androidx.activity:activity:1.0.0-alpha02"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_runtime",
            ":androidx_lifecycle__lifecycle_viewmodel",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_runtime",
            ":androidx_lifecycle__lifecycle_viewmodel",
        ],
    )

    # from androidx.annotation:annotation:1.0.0
    native.alias(
        name = "androidx_annotation__annotation",
        actual = ":androidx_annotation__annotation__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.annotation:annotation:1.0.0
    java_import(
        name = "androidx_annotation__annotation__1_0_0",
        jars = ["@androidx_annotation__annotation__1_0_0//file"],
        tags = ["maven_coordinates=androidx.annotation:annotation:1.0.0"],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from androidx.appcompat:appcompat:1.0.2
    native.alias(
        name = "androidx_appcompat__appcompat",
        actual = ":androidx_appcompat__appcompat__1_0_2",
        visibility = ["//visibility:public"],
    )

    # from androidx.appcompat:appcompat:1.0.2
    aar_import(
        name = "androidx_appcompat__appcompat__1_0_2",
        aar = "@androidx_appcompat__appcompat__1_0_2//file",
        tags = ["maven_coordinates=androidx.appcompat:appcompat:1.0.2"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
            ":androidx_core__core",
            ":androidx_cursoradapter__cursoradapter",
            ":androidx_fragment__fragment",
            ":androidx_legacy__legacy_support_core_utils",
            ":androidx_vectordrawable__vectordrawable",
            ":androidx_vectordrawable__vectordrawable_animated",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
            ":androidx_core__core",
            ":androidx_cursoradapter__cursoradapter",
            ":androidx_fragment__fragment",
            ":androidx_legacy__legacy_support_core_utils",
            ":androidx_vectordrawable__vectordrawable",
            ":androidx_vectordrawable__vectordrawable_animated",
        ],
    )

    # from androidx.arch.core:core-common:2.0.0
    native.alias(
        name = "androidx_arch_core__core_common",
        actual = ":androidx_arch_core__core_common__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.arch.core:core-common:2.0.0
    java_import(
        name = "androidx_arch_core__core_common__2_0_0",
        jars = ["@androidx_arch_core__core_common__2_0_0//file"],
        tags = ["maven_coordinates=androidx.arch.core:core-common:2.0.0"],
        licenses = ["notice"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
        runtime_deps = [],
    )

    # from androidx.arch.core:core-runtime:2.0.0
    native.alias(
        name = "androidx_arch_core__core_runtime",
        actual = ":androidx_arch_core__core_runtime__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.arch.core:core-runtime:2.0.0
    aar_import(
        name = "androidx_arch_core__core_runtime__2_0_0",
        aar = "@androidx_arch_core__core_runtime__2_0_0//file",
        tags = ["maven_coordinates=androidx.arch.core:core-runtime:2.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_arch_core__core_common",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_arch_core__core_common",
        ],
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    native.alias(
        name = "androidx_asynclayoutinflater__asynclayoutinflater",
        actual = ":androidx_asynclayoutinflater__asynclayoutinflater__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    aar_import(
        name = "androidx_asynclayoutinflater__asynclayoutinflater__1_0_0",
        aar = "@androidx_asynclayoutinflater__asynclayoutinflater__1_0_0//file",
        tags = ["maven_coordinates=androidx.asynclayoutinflater:asynclayoutinflater:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
    )

    # from androidx.collection:collection:1.0.0
    native.alias(
        name = "androidx_collection__collection",
        actual = ":androidx_collection__collection__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.collection:collection:1.0.0
    java_import(
        name = "androidx_collection__collection__1_0_0",
        jars = ["@androidx_collection__collection__1_0_0//file"],
        tags = ["maven_coordinates=androidx.collection:collection:1.0.0"],
        licenses = ["notice"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
        runtime_deps = [],
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    native.alias(
        name = "androidx_coordinatorlayout__coordinatorlayout",
        actual = ":androidx_coordinatorlayout__coordinatorlayout__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    aar_import(
        name = "androidx_coordinatorlayout__coordinatorlayout__1_0_0",
        aar = "@androidx_coordinatorlayout__coordinatorlayout__1_0_0//file",
        tags = ["maven_coordinates=androidx.coordinatorlayout:coordinatorlayout:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
    )

    # from androidx.core:core:1.1.0-alpha01
    native.alias(
        name = "androidx_core__core",
        actual = ":androidx_core__core__1_1_0_alpha01",
        visibility = ["//visibility:public"],
    )

    # from androidx.core:core:1.1.0-alpha01
    aar_import(
        name = "androidx_core__core__1_1_0_alpha01",
        aar = "@androidx_core__core__1_1_0_alpha01//file",
        tags = ["maven_coordinates=androidx.core:core:1.1.0-alpha01"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
            ":androidx_lifecycle__lifecycle_runtime",
            ":androidx_versionedparcelable__versionedparcelable",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
            ":androidx_lifecycle__lifecycle_runtime",
            ":androidx_versionedparcelable__versionedparcelable",
        ],
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    native.alias(
        name = "androidx_cursoradapter__cursoradapter",
        actual = ":androidx_cursoradapter__cursoradapter__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    aar_import(
        name = "androidx_cursoradapter__cursoradapter__1_0_0",
        aar = "@androidx_cursoradapter__cursoradapter__1_0_0//file",
        tags = ["maven_coordinates=androidx.cursoradapter:cursoradapter:1.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.customview:customview:1.0.0
    native.alias(
        name = "androidx_customview__customview",
        actual = ":androidx_customview__customview__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.customview:customview:1.0.0
    aar_import(
        name = "androidx_customview__customview__1_0_0",
        aar = "@androidx_customview__customview__1_0_0//file",
        tags = ["maven_coordinates=androidx.customview:customview:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
    )

    # from androidx.documentfile:documentfile:1.0.0
    native.alias(
        name = "androidx_documentfile__documentfile",
        actual = ":androidx_documentfile__documentfile__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.documentfile:documentfile:1.0.0
    aar_import(
        name = "androidx_documentfile__documentfile__1_0_0",
        aar = "@androidx_documentfile__documentfile__1_0_0//file",
        tags = ["maven_coordinates=androidx.documentfile:documentfile:1.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    native.alias(
        name = "androidx_drawerlayout__drawerlayout",
        actual = ":androidx_drawerlayout__drawerlayout__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    aar_import(
        name = "androidx_drawerlayout__drawerlayout__1_0_0",
        aar = "@androidx_drawerlayout__drawerlayout__1_0_0//file",
        tags = ["maven_coordinates=androidx.drawerlayout:drawerlayout:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    native.alias(
        name = "androidx_fragment__fragment",
        actual = ":androidx_fragment__fragment__1_1_0_alpha02",
        visibility = ["//visibility:public"],
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    aar_import(
        name = "androidx_fragment__fragment__1_1_0_alpha02",
        aar = "@androidx_fragment__fragment__1_1_0_alpha02//file",
        tags = ["maven_coordinates=androidx.fragment:fragment:1.1.0-alpha02"],
        deps = [
            ":androidx_activity__activity",
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_viewmodel",
            ":androidx_loader__loader",
            ":androidx_viewpager__viewpager",
        ],
        exports = [
            ":androidx_activity__activity",
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_viewmodel",
            ":androidx_loader__loader",
            ":androidx_viewpager__viewpager",
        ],
    )

    # from androidx.interpolator:interpolator:1.0.0
    native.alias(
        name = "androidx_interpolator__interpolator",
        actual = ":androidx_interpolator__interpolator__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.interpolator:interpolator:1.0.0
    aar_import(
        name = "androidx_interpolator__interpolator__1_0_0",
        aar = "@androidx_interpolator__interpolator__1_0_0//file",
        tags = ["maven_coordinates=androidx.interpolator:interpolator:1.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    native.alias(
        name = "androidx_legacy__legacy_support_core_ui",
        actual = ":androidx_legacy__legacy_support_core_ui__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    aar_import(
        name = "androidx_legacy__legacy_support_core_ui__1_0_0",
        aar = "@androidx_legacy__legacy_support_core_ui__1_0_0//file",
        tags = ["maven_coordinates=androidx.legacy:legacy-support-core-ui:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_asynclayoutinflater__asynclayoutinflater",
            ":androidx_coordinatorlayout__coordinatorlayout",
            ":androidx_core__core",
            ":androidx_cursoradapter__cursoradapter",
            ":androidx_customview__customview",
            ":androidx_drawerlayout__drawerlayout",
            ":androidx_interpolator__interpolator",
            ":androidx_legacy__legacy_support_core_utils",
            ":androidx_slidingpanelayout__slidingpanelayout",
            ":androidx_swiperefreshlayout__swiperefreshlayout",
            ":androidx_viewpager__viewpager",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_asynclayoutinflater__asynclayoutinflater",
            ":androidx_coordinatorlayout__coordinatorlayout",
            ":androidx_core__core",
            ":androidx_cursoradapter__cursoradapter",
            ":androidx_customview__customview",
            ":androidx_drawerlayout__drawerlayout",
            ":androidx_interpolator__interpolator",
            ":androidx_legacy__legacy_support_core_utils",
            ":androidx_slidingpanelayout__slidingpanelayout",
            ":androidx_swiperefreshlayout__swiperefreshlayout",
            ":androidx_viewpager__viewpager",
        ],
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    native.alias(
        name = "androidx_legacy__legacy_support_core_utils",
        actual = ":androidx_legacy__legacy_support_core_utils__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    aar_import(
        name = "androidx_legacy__legacy_support_core_utils__1_0_0",
        aar = "@androidx_legacy__legacy_support_core_utils__1_0_0//file",
        tags = ["maven_coordinates=androidx.legacy:legacy-support-core-utils:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_documentfile__documentfile",
            ":androidx_loader__loader",
            ":androidx_localbroadcastmanager__localbroadcastmanager",
            ":androidx_print__print",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_documentfile__documentfile",
            ":androidx_loader__loader",
            ":androidx_localbroadcastmanager__localbroadcastmanager",
            ":androidx_print__print",
        ],
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    native.alias(
        name = "androidx_lifecycle__lifecycle_common",
        actual = ":androidx_lifecycle__lifecycle_common__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    java_import(
        name = "androidx_lifecycle__lifecycle_common__2_0_0",
        jars = ["@androidx_lifecycle__lifecycle_common__2_0_0//file"],
        tags = ["maven_coordinates=androidx.lifecycle:lifecycle-common:2.0.0"],
        licenses = ["notice"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
        runtime_deps = [],
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    native.alias(
        name = "androidx_lifecycle__lifecycle_livedata_core",
        actual = ":androidx_lifecycle__lifecycle_livedata_core__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    aar_import(
        name = "androidx_lifecycle__lifecycle_livedata_core__2_0_0",
        aar = "@androidx_lifecycle__lifecycle_livedata_core__2_0_0//file",
        tags = ["maven_coordinates=androidx.lifecycle:lifecycle-livedata-core:2.0.0"],
        deps = [
            ":androidx_arch_core__core_common",
            ":androidx_arch_core__core_runtime",
            ":androidx_lifecycle__lifecycle_common",
        ],
        exports = [
            ":androidx_arch_core__core_common",
            ":androidx_arch_core__core_runtime",
            ":androidx_lifecycle__lifecycle_common",
        ],
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    native.alias(
        name = "androidx_lifecycle__lifecycle_livedata",
        actual = ":androidx_lifecycle__lifecycle_livedata__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    aar_import(
        name = "androidx_lifecycle__lifecycle_livedata__2_0_0",
        aar = "@androidx_lifecycle__lifecycle_livedata__2_0_0//file",
        tags = ["maven_coordinates=androidx.lifecycle:lifecycle-livedata:2.0.0"],
        deps = [
            ":androidx_arch_core__core_common",
            ":androidx_arch_core__core_runtime",
            ":androidx_lifecycle__lifecycle_livedata_core",
        ],
        exports = [
            ":androidx_arch_core__core_common",
            ":androidx_arch_core__core_runtime",
            ":androidx_lifecycle__lifecycle_livedata_core",
        ],
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    native.alias(
        name = "androidx_lifecycle__lifecycle_runtime",
        actual = ":androidx_lifecycle__lifecycle_runtime__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    aar_import(
        name = "androidx_lifecycle__lifecycle_runtime__2_0_0",
        aar = "@androidx_lifecycle__lifecycle_runtime__2_0_0//file",
        tags = ["maven_coordinates=androidx.lifecycle:lifecycle-runtime:2.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_arch_core__core_common",
            ":androidx_lifecycle__lifecycle_common",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_arch_core__core_common",
            ":androidx_lifecycle__lifecycle_common",
        ],
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    native.alias(
        name = "androidx_lifecycle__lifecycle_viewmodel",
        actual = ":androidx_lifecycle__lifecycle_viewmodel__2_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    aar_import(
        name = "androidx_lifecycle__lifecycle_viewmodel__2_0_0",
        aar = "@androidx_lifecycle__lifecycle_viewmodel__2_0_0//file",
        tags = ["maven_coordinates=androidx.lifecycle:lifecycle-viewmodel:2.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.loader:loader:1.0.0
    native.alias(
        name = "androidx_loader__loader",
        actual = ":androidx_loader__loader__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.loader:loader:1.0.0
    aar_import(
        name = "androidx_loader__loader__1_0_0",
        aar = "@androidx_loader__loader__1_0_0//file",
        tags = ["maven_coordinates=androidx.loader:loader:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_livedata",
            ":androidx_lifecycle__lifecycle_viewmodel",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_lifecycle__lifecycle_livedata",
            ":androidx_lifecycle__lifecycle_viewmodel",
        ],
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    native.alias(
        name = "androidx_localbroadcastmanager__localbroadcastmanager",
        actual = ":androidx_localbroadcastmanager__localbroadcastmanager__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    aar_import(
        name = "androidx_localbroadcastmanager__localbroadcastmanager__1_0_0",
        aar = "@androidx_localbroadcastmanager__localbroadcastmanager__1_0_0//file",
        tags = ["maven_coordinates=androidx.localbroadcastmanager:localbroadcastmanager:1.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.print:print:1.0.0
    native.alias(
        name = "androidx_print__print",
        actual = ":androidx_print__print__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.print:print:1.0.0
    aar_import(
        name = "androidx_print__print__1_0_0",
        aar = "@androidx_print__print__1_0_0//file",
        tags = ["maven_coordinates=androidx.print:print:1.0.0"],
        deps = [":androidx_annotation__annotation"],
        exports = [":androidx_annotation__annotation"],
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    native.alias(
        name = "androidx_slidingpanelayout__slidingpanelayout",
        actual = ":androidx_slidingpanelayout__slidingpanelayout__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    aar_import(
        name = "androidx_slidingpanelayout__slidingpanelayout__1_0_0",
        aar = "@androidx_slidingpanelayout__slidingpanelayout__1_0_0//file",
        tags = ["maven_coordinates=androidx.slidingpanelayout:slidingpanelayout:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    native.alias(
        name = "androidx_swiperefreshlayout__swiperefreshlayout",
        actual = ":androidx_swiperefreshlayout__swiperefreshlayout__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    aar_import(
        name = "androidx_swiperefreshlayout__swiperefreshlayout__1_0_0",
        aar = "@androidx_swiperefreshlayout__swiperefreshlayout__1_0_0//file",
        tags = ["maven_coordinates=androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_interpolator__interpolator",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_interpolator__interpolator",
        ],
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    native.alias(
        name = "androidx_vectordrawable__vectordrawable_animated",
        actual = ":androidx_vectordrawable__vectordrawable_animated__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    aar_import(
        name = "androidx_vectordrawable__vectordrawable_animated__1_0_0",
        aar = "@androidx_vectordrawable__vectordrawable_animated__1_0_0//file",
        tags = ["maven_coordinates=androidx.vectordrawable:vectordrawable-animated:1.0.0"],
        deps = [
            ":androidx_legacy__legacy_support_core_ui",
            ":androidx_vectordrawable__vectordrawable",
        ],
        exports = [
            ":androidx_legacy__legacy_support_core_ui",
            ":androidx_vectordrawable__vectordrawable",
        ],
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    native.alias(
        name = "androidx_vectordrawable__vectordrawable",
        actual = ":androidx_vectordrawable__vectordrawable__1_0_1",
        visibility = ["//visibility:public"],
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    aar_import(
        name = "androidx_vectordrawable__vectordrawable__1_0_1",
        aar = "@androidx_vectordrawable__vectordrawable__1_0_1//file",
        tags = ["maven_coordinates=androidx.vectordrawable:vectordrawable:1.0.1"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
        ],
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    native.alias(
        name = "androidx_versionedparcelable__versionedparcelable",
        actual = ":androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01",
        visibility = ["//visibility:public"],
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    aar_import(
        name = "androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01",
        aar = "@androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01//file",
        tags = ["maven_coordinates=androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_collection__collection",
        ],
    )

    # from androidx.viewpager:viewpager:1.0.0
    native.alias(
        name = "androidx_viewpager__viewpager",
        actual = ":androidx_viewpager__viewpager__1_0_0",
        visibility = ["//visibility:public"],
    )

    # from androidx.viewpager:viewpager:1.0.0
    aar_import(
        name = "androidx_viewpager__viewpager__1_0_0",
        aar = "@androidx_viewpager__viewpager__1_0_0//file",
        tags = ["maven_coordinates=androidx.viewpager:viewpager:1.0.0"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
        exports = [
            ":androidx_annotation__annotation",
            ":androidx_core__core",
            ":androidx_customview__customview",
        ],
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    native.alias(
        name = "com_github_menny_Chauffeur__lib",
        actual = ":com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406",
        visibility = ["//visibility:public"],
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    aar_import(
        name = "com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406",
        aar = "@com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406//file",
        tags = ["maven_coordinates=com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_appcompat__appcompat",
            ":androidx_fragment__fragment",
        ],
        exports = [],
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    native.alias(
        name = "com_github_menny_Chauffeur__permissions",
        actual = ":com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406",
        visibility = ["//visibility:public"],
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    aar_import(
        name = "com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406",
        aar = "@com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406//file",
        tags = ["maven_coordinates=com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406"],
        deps = [
            ":androidx_annotation__annotation",
            ":androidx_appcompat__appcompat",
            ":androidx_fragment__fragment",
            ":com_github_menny_Chauffeur__lib",
        ],
        exports = [":com_github_menny_Chauffeur__lib"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi_kotlin_codegen",
        actual = ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    kt_jvm_library(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2",
        tags = ["maven_coordinates=com.squareup.moshi:moshi-kotlin-codegen:1.9.2"],
        exports = [
            ":com_squareup__kotlinpoet",
            ":com_squareup_moshi__moshi",
            ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2_kt_jvm_import",
            ":org_jetbrains_kotlin__kotlin_stdlib",
        ],
        runtime_deps = [],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    java_plugin(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2___generates_api___processor_class_0",
        processor_class = "com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor",
        generates_api = 1,
        deps = [
            ":com_squareup__kotlinpoet",
            ":com_squareup_moshi__moshi",
            ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2",
            ":org_jetbrains_kotlin__kotlin_stdlib",
        ],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    java_library(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2___generates_api___processor_class_all",
        exported_plugins = [":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___generates_api___processor_class_0"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    java_plugin(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2___processor_class_0",
        processor_class = "com.squareup.moshi.kotlin.codegen.JsonClassCodegenProcessor",
        generates_api = 0,
        deps = [
            ":com_squareup__kotlinpoet",
            ":com_squareup_moshi__moshi",
            ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2",
            ":org_jetbrains_kotlin__kotlin_stdlib",
        ],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    java_library(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2___processor_class_all",
        exported_plugins = [":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___processor_class_0"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    kt_jvm_import(
        name = "com_squareup_moshi__moshi_kotlin_codegen__1_9_2_kt_jvm_import",
        jar = "@com_squareup_moshi__moshi_kotlin_codegen__1_9_2//file",
        visibility = ["//visibility:private"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi_kotlin_codegen___generates_api___processor_class_0",
        actual = ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___generates_api___processor_class_0",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi_kotlin_codegen___generates_api___processor_class_all",
        actual = ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___generates_api___processor_class_all",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi_kotlin_codegen___processor_class_0",
        actual = ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___processor_class_0",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi-kotlin-codegen:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi_kotlin_codegen___processor_class_all",
        actual = ":com_squareup_moshi__moshi_kotlin_codegen__1_9_2___processor_class_all",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi:1.9.2
    native.alias(
        name = "com_squareup_moshi__moshi",
        actual = ":com_squareup_moshi__moshi__1_9_2",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.moshi:moshi:1.9.2
    java_import(
        name = "com_squareup_moshi__moshi__1_9_2",
        jars = ["@com_squareup_moshi__moshi__1_9_2//file"],
        tags = ["maven_coordinates=com.squareup.moshi:moshi:1.9.2"],
        licenses = ["notice"],
        deps = [":com_squareup_okio__okio"],
        exports = [":com_squareup_okio__okio"],
        runtime_deps = [],
    )

    # from com.squareup.okio:okio:1.16.0
    native.alias(
        name = "com_squareup_okio__okio",
        actual = ":com_squareup_okio__okio__1_16_0",
        visibility = ["//visibility:public"],
    )

    # from com.squareup.okio:okio:1.16.0
    java_import(
        name = "com_squareup_okio__okio__1_16_0",
        jars = ["@com_squareup_okio__okio__1_16_0//file"],
        tags = ["maven_coordinates=com.squareup.okio:okio:1.16.0"],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from com.squareup:kotlinpoet:1.4.4
    native.alias(
        name = "com_squareup__kotlinpoet",
        actual = ":com_squareup__kotlinpoet__1_4_4",
        visibility = ["//visibility:public"],
    )

    # from com.squareup:kotlinpoet:1.4.4
    kt_jvm_library(
        name = "com_squareup__kotlinpoet__1_4_4",
        tags = ["maven_coordinates=com.squareup:kotlinpoet:1.4.4"],
        exports = [
            ":com_squareup__kotlinpoet__1_4_4_kt_jvm_import",
            ":org_jetbrains_kotlin__kotlin_stdlib_jdk7",
        ],
        runtime_deps = [":org_jetbrains_kotlin__kotlin_reflect"],
    )

    # from com.squareup:kotlinpoet:1.4.4
    kt_jvm_import(
        name = "com_squareup__kotlinpoet__1_4_4_kt_jvm_import",
        jar = "@com_squareup__kotlinpoet__1_4_4//file",
        visibility = ["//visibility:private"],
    )

    # from org.jetbrains.kotlin:kotlin-reflect:1.3.50
    native.alias(
        name = "org_jetbrains_kotlin__kotlin_reflect",
        actual = ":org_jetbrains_kotlin__kotlin_reflect__1_3_50",
        visibility = ["//visibility:public"],
    )

    # from org.jetbrains.kotlin:kotlin-reflect:1.3.50
    kt_jvm_library(
        name = "org_jetbrains_kotlin__kotlin_reflect__1_3_50",
        tags = ["maven_coordinates=org.jetbrains.kotlin:kotlin-reflect:1.3.50"],
        exports = [
            ":org_jetbrains_kotlin__kotlin_reflect__1_3_50_kt_jvm_import",
            ":org_jetbrains_kotlin__kotlin_stdlib",
        ],
        runtime_deps = [],
    )

    # from org.jetbrains.kotlin:kotlin-reflect:1.3.50
    kt_jvm_import(
        name = "org_jetbrains_kotlin__kotlin_reflect__1_3_50_kt_jvm_import",
        jar = "@org_jetbrains_kotlin__kotlin_reflect__1_3_50//file",
        visibility = ["//visibility:private"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
    native.alias(
        name = "org_jetbrains_kotlin__kotlin_stdlib_common",
        actual = ":org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72",
        visibility = ["//visibility:public"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
    kt_jvm_library(
        name = "org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72",
        tags = ["maven_coordinates=org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72"],
        exports = [":org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72_kt_jvm_import"],
        runtime_deps = [],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
    kt_jvm_import(
        name = "org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72_kt_jvm_import",
        jar = "@org_jetbrains_kotlin__kotlin_stdlib_common__1_3_72//file",
        visibility = ["//visibility:private"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
    native.alias(
        name = "org_jetbrains_kotlin__kotlin_stdlib_jdk7",
        actual = ":org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50",
        visibility = ["//visibility:public"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
    kt_jvm_library(
        name = "org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50",
        tags = ["maven_coordinates=org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50"],
        exports = [
            ":org_jetbrains_kotlin__kotlin_stdlib",
            ":org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50_kt_jvm_import",
        ],
        runtime_deps = [],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
    kt_jvm_import(
        name = "org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50_kt_jvm_import",
        jar = "@org_jetbrains_kotlin__kotlin_stdlib_jdk7__1_3_50//file",
        visibility = ["//visibility:private"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib:1.3.72
    native.alias(
        name = "org_jetbrains_kotlin__kotlin_stdlib",
        actual = ":org_jetbrains_kotlin__kotlin_stdlib__1_3_72",
        visibility = ["//visibility:public"],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib:1.3.72
    kt_jvm_library(
        name = "org_jetbrains_kotlin__kotlin_stdlib__1_3_72",
        tags = ["maven_coordinates=org.jetbrains.kotlin:kotlin-stdlib:1.3.72"],
        exports = [
            ":org_jetbrains__annotations",
            ":org_jetbrains_kotlin__kotlin_stdlib__1_3_72_kt_jvm_import",
            ":org_jetbrains_kotlin__kotlin_stdlib_common",
        ],
        runtime_deps = [],
    )

    # from org.jetbrains.kotlin:kotlin-stdlib:1.3.72
    kt_jvm_import(
        name = "org_jetbrains_kotlin__kotlin_stdlib__1_3_72_kt_jvm_import",
        jar = "@org_jetbrains_kotlin__kotlin_stdlib__1_3_72//file",
        visibility = ["//visibility:private"],
    )

    # from org.jetbrains:annotations:13.0
    native.alias(
        name = "org_jetbrains__annotations",
        actual = ":org_jetbrains__annotations__13_0",
        visibility = ["//visibility:public"],
    )

    # from org.jetbrains:annotations:13.0
    java_import(
        name = "org_jetbrains__annotations__13_0",
        jars = ["@org_jetbrains__annotations__13_0//file"],
        tags = ["maven_coordinates=org.jetbrains:annotations:13.0"],
        licenses = ["notice"],
        deps = [],
        exports = [],
        runtime_deps = [],
    )
