"""
Required macros for creating repository-rules and third-party Maven dependencies.

Auto-generated by https://github.com/menny/mabel
"""

# Loading a drop-in replacement for native.http_file
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

def generate_workspace_rules(name = "generate_workspace_rules"):
    """
    Repository rules macro to be run in the WORKSPACE file.

    Args:
        name: A unique name for this target. No need to specify.
    """

    # from com.beust:jcommander:1.72
    http_file(
        name = "com_beust__jcommander__1_72",
        urls = ["https://repo1.maven.org/maven2/com/beust/jcommander/1.72/jcommander-1.72.jar"],
        downloaded_file_path = "jcommander-1.72.jar",
        sha256 = "e0de160b129b2414087e01fe845609cd55caec6820cfd4d0c90fabcc7bdb8c1e",
    )

    # from com.google.auto.value:auto-value-annotations:1.7
    http_file(
        name = "com_google_auto_value__auto_value_annotations__1_7",
        urls = ["https://repo1.maven.org/maven2/com/google/auto/value/auto-value-annotations/1.7/auto-value-annotations-1.7.jar"],
        downloaded_file_path = "auto-value-annotations-1.7.jar",
        sha256 = "b134bab5082e9f49f2b45802573c78e0726e059b645323645da03e328e501f86",
    )

    # from com.google.auto.value:auto-value:1.7
    http_file(
        name = "com_google_auto_value__auto_value__1_7",
        urls = ["https://repo1.maven.org/maven2/com/google/auto/value/auto-value/1.7/auto-value-1.7.jar"],
        downloaded_file_path = "auto-value-1.7.jar",
        sha256 = "b66df6984d5c29f15a6253514c817fb046e8e242efffc79e42c33f2dde0edf41",
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    http_file(
        name = "com_google_code_findbugs__jsr305__3_0_2",
        urls = ["https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar"],
        downloaded_file_path = "jsr305-3.0.2.jar",
        sha256 = "766ad2a0783f2687962c8ad74ceecc38a28b9f72a2d085ee438b7813e928d0c7",
    )

    # from com.google.code.gson:gson:2.8.5
    http_file(
        name = "com_google_code_gson__gson__2_8_5",
        urls = ["https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar"],
        downloaded_file_path = "gson-2.8.5.jar",
        sha256 = "233a0149fc365c9f6edbd683cfe266b19bdc773be98eabdaf6b3c924b48e7d81",
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    http_file(
        name = "com_google_errorprone__error_prone_annotations__2_2_0",
        urls = ["https://repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.2.0/error_prone_annotations-2.2.0.jar"],
        downloaded_file_path = "error_prone_annotations-2.2.0.jar",
        sha256 = "6ebd22ca1b9d8ec06d41de8d64e0596981d9607b42035f9ed374f9de271a481a",
    )

    # from com.google.guava:failureaccess:1.0.1
    http_file(
        name = "com_google_guava__failureaccess__1_0_1",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar"],
        downloaded_file_path = "failureaccess-1.0.1.jar",
        sha256 = "a171ee4c734dd2da837e4b16be9df4661afab72a41adaf31eb84dfdaf936ca26",
    )

    # from com.google.guava:guava:27.0.1-jre
    http_file(
        name = "com_google_guava__guava__27_0_1_jre",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar"],
        downloaded_file_path = "guava-27.0.1-jre.jar",
        sha256 = "e1c814fd04492a27c38e0317eabeaa1b3e950ec8010239e400fe90ad6c9107b4",
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    http_file(
        name = "com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        urls = ["https://repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar"],
        downloaded_file_path = "listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar",
        sha256 = "b372a037d4230aa57fbeffdef30fd6123f9c0c2db85d0aced00c91b974f33f99",
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    http_file(
        name = "com_google_j2objc__j2objc_annotations__1_1",
        urls = ["https://repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar"],
        downloaded_file_path = "j2objc-annotations-1.1.jar",
        sha256 = "2994a7eb78f2710bd3d3bfb639b2c94e219cedac0d4d084d516e78c16dddecf6",
    )

    # from commons-codec:commons-codec:1.11
    http_file(
        name = "commons_codec__commons_codec__1_11",
        urls = ["https://repo1.maven.org/maven2/commons-codec/commons-codec/1.11/commons-codec-1.11.jar"],
        downloaded_file_path = "commons-codec-1.11.jar",
        sha256 = "e599d5318e97aa48f42136a2927e6dfa4e8881dff0e6c8e3109ddbbff51d7b7d",
    )

    # from commons-logging:commons-logging:1.2
    http_file(
        name = "commons_logging__commons_logging__1_2",
        urls = ["https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar"],
        downloaded_file_path = "commons-logging-1.2.jar",
        sha256 = "daddea1ea0be0f56978ab3006b8ac92834afeefbd9b7e4e6316fca57df0fa636",
    )

    # from javax.inject:javax.inject:1
    http_file(
        name = "javax_inject__javax_inject__1",
        urls = ["https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar"],
        downloaded_file_path = "javax.inject-1.jar",
        sha256 = "91c77044a50c481636c32d916fd89c9118a72195390452c81065080f957de7ff",
    )

    # from junit:junit:4.12
    http_file(
        name = "junit__junit__4_12",
        urls = ["https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar"],
        downloaded_file_path = "junit-4.12.jar",
        sha256 = "59721f0805e223d84b90677887d9ff567dc534d7c502ca903c0c2b17f05c116a",
    )

    # from net.bytebuddy:byte-buddy-agent:1.9.3
    http_file(
        name = "net_bytebuddy__byte_buddy_agent__1_9_3",
        urls = ["https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy-agent/1.9.3/byte-buddy-agent-1.9.3.jar"],
        downloaded_file_path = "byte-buddy-agent-1.9.3.jar",
        sha256 = "547288e013a9d1f4a4ce2ab84c24e3edda6e433c7fa6b2c3c3613932671b05b1",
    )

    # from net.bytebuddy:byte-buddy:1.9.3
    http_file(
        name = "net_bytebuddy__byte_buddy__1_9_3",
        urls = ["https://repo1.maven.org/maven2/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3.jar"],
        downloaded_file_path = "byte-buddy-1.9.3.jar",
        sha256 = "a27350be602caea67a33d31281496c84c69b5ab34ddc228e9ff2253fc8f9cd31",
    )

    # from org.apache.commons:commons-lang3:3.8.1
    http_file(
        name = "org_apache_commons__commons_lang3__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar"],
        downloaded_file_path = "commons-lang3-3.8.1.jar",
        sha256 = "dac807f65b07698ff39b1b07bfef3d87ae3fd46d91bbf8a2bc02b2a831616f68",
    )

    # from org.apache.httpcomponents:httpclient:4.5.13
    http_file(
        name = "org_apache_httpcomponents__httpclient__4_5_13",
        urls = ["https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar"],
        downloaded_file_path = "httpclient-4.5.13.jar",
        sha256 = "6fe9026a566c6a5001608cf3fc32196641f6c1e5e1986d1037ccdbd5f31ef743",
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    http_file(
        name = "org_apache_httpcomponents__httpcore__4_4_13",
        urls = ["https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar"],
        downloaded_file_path = "httpcore-4.4.13.jar",
        sha256 = "e06e89d40943245fcfa39ec537cdbfce3762aecde8f9c597780d2b00c2b43424",
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0
    http_file(
        name = "org_apache_maven_wagon__wagon_provider_api__1_0",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/wagon/wagon-provider-api/1.0/wagon-provider-api-1.0.jar"],
        downloaded_file_path = "wagon-provider-api-1.0.jar",
        sha256 = "b28dd1302ac34433d8d1b45fb254e093cd7b47277441af2018c8a3a4d8c1a60d",
    )

    # from org.apache.maven:maven-aether-provider:3.3.9
    http_file(
        name = "org_apache_maven__maven_aether_provider__3_3_9",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-aether-provider/3.3.9/maven-aether-provider-3.3.9.jar"],
        downloaded_file_path = "maven-aether-provider-3.3.9.jar",
        sha256 = "f46962583d812cd4459a4cc963113b9c52f1f9b169172354693bc9efa0b3e3cb",
    )

    # from org.apache.maven:maven-artifact:3.8.1
    http_file(
        name = "org_apache_maven__maven_artifact__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-artifact/3.8.1/maven-artifact-3.8.1.jar"],
        downloaded_file_path = "maven-artifact-3.8.1.jar",
        sha256 = "9dbd3db15ac4816471e72981cb06ef90f3ffa8be6628dddf7135f7bd69bee0c0",
    )

    # from org.apache.maven:maven-builder-support:3.8.1
    http_file(
        name = "org_apache_maven__maven_builder_support__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-builder-support/3.8.1/maven-builder-support-3.8.1.jar"],
        downloaded_file_path = "maven-builder-support-3.8.1.jar",
        sha256 = "04ca8710b375c30bdb78964c24d665b866bc0f096cc2a93c82aa43f9e331c36b",
    )

    # from org.apache.maven:maven-model-builder:3.8.1
    http_file(
        name = "org_apache_maven__maven_model_builder__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-model-builder/3.8.1/maven-model-builder-3.8.1.jar"],
        downloaded_file_path = "maven-model-builder-3.8.1.jar",
        sha256 = "60efee1229626229c13febb6d6c1949120c6ab55ced0e9ce16cd167a0056b8e1",
    )

    # from org.apache.maven:maven-model:3.8.1
    http_file(
        name = "org_apache_maven__maven_model__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.8.1/maven-model-3.8.1.jar"],
        downloaded_file_path = "maven-model-3.8.1.jar",
        sha256 = "9e008629cefa5ddc9e5e2628adb467416ced250591e30dea7103f37f513b3b13",
    )

    # from org.apache.maven:maven-repository-metadata:3.8.1
    http_file(
        name = "org_apache_maven__maven_repository_metadata__3_8_1",
        urls = ["https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.8.1/maven-repository-metadata-3.8.1.jar"],
        downloaded_file_path = "maven-repository-metadata-3.8.1.jar",
        sha256 = "ed400ae8d4782e8b865571637c5244e3b79fea4829b8a0870c714c1094f2dda5",
    )

    # from org.checkerframework:checker-qual:2.5.2
    http_file(
        name = "org_checkerframework__checker_qual__2_5_2",
        urls = ["https://repo1.maven.org/maven2/org/checkerframework/checker-qual/2.5.2/checker-qual-2.5.2.jar"],
        downloaded_file_path = "checker-qual-2.5.2.jar",
        sha256 = "64b02691c8b9d4e7700f8ee2e742dce7ea2c6e81e662b7522c9ee3bf568c040a",
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    http_file(
        name = "org_codehaus_mojo__animal_sniffer_annotations__1_17",
        urls = ["https://repo1.maven.org/maven2/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar"],
        downloaded_file_path = "animal-sniffer-annotations-1.17.jar",
        sha256 = "92654f493ecfec52082e76354f0ebf87648dc3d5cec2e3c3cdb947c016747a53",
    )

    # from org.codehaus.plexus:plexus-component-annotations:1.6
    http_file(
        name = "org_codehaus_plexus__plexus_component_annotations__1_6",
        urls = ["https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar"],
        downloaded_file_path = "plexus-component-annotations-1.6.jar",
        sha256 = "2b3a6ca5f19a9ad490bc233f45e68d3093c8c01b4acc3c1d14bad4ca7c7ff438",
    )

    # from org.codehaus.plexus:plexus-interpolation:1.26
    http_file(
        name = "org_codehaus_plexus__plexus_interpolation__1_26",
        urls = ["https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.26/plexus-interpolation-1.26.jar"],
        downloaded_file_path = "plexus-interpolation-1.26.jar",
        sha256 = "b3b5412ce17889103ea564bcdfcf9fb3dfa540344ffeac6b538a73c9d7182662",
    )

    # from org.codehaus.plexus:plexus-utils:3.3.0
    http_file(
        name = "org_codehaus_plexus__plexus_utils__3_3_0",
        urls = ["https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-utils/3.3.0/plexus-utils-3.3.0.jar"],
        downloaded_file_path = "plexus-utils-3.3.0.jar",
        sha256 = "76d174792540e2775af94d03d10fb2d3c776e2cd0ac0ebf427d3e570072bb9ce",
    )

    # from org.eclipse.aether:aether-api:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_api__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-api/1.1.0/aether-api-1.1.0.jar"],
        downloaded_file_path = "aether-api-1.1.0.jar",
        sha256 = "e196bd5e61c5fc3139fb3d12161b122ce657bab6a34c38f1e338a3aab18992f5",
    )

    # from org.eclipse.aether:aether-connector-basic:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_connector_basic__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-connector-basic/1.1.0/aether-connector-basic-1.1.0.jar"],
        downloaded_file_path = "aether-connector-basic-1.1.0.jar",
        sha256 = "4431d8edf172815349a444a34376aa3229f89952d01bae748f42c5f0b4680d93",
    )

    # from org.eclipse.aether:aether-impl:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_impl__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-impl/1.1.0/aether-impl-1.1.0.jar"],
        downloaded_file_path = "aether-impl-1.1.0.jar",
        sha256 = "0bf7dfbbcde79ce0ded7712f191c7ecd28f5a4fa16f4f6bfbfaa7c2f98e5c234",
    )

    # from org.eclipse.aether:aether-spi:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_spi__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-spi/1.1.0/aether-spi-1.1.0.jar"],
        downloaded_file_path = "aether-spi-1.1.0.jar",
        sha256 = "dd9e79b759f813269ff15f849c9ebb1999bd7bc988e2b399f7581089fd368acb",
    )

    # from org.eclipse.aether:aether-transport-classpath:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_transport_classpath__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-transport-classpath/1.1.0/aether-transport-classpath-1.1.0.jar"],
        downloaded_file_path = "aether-transport-classpath-1.1.0.jar",
        sha256 = "036cd51c716d002aeec1adb62f8ba99d1a1efa4d258cc07954576ad599de8bc9",
    )

    # from org.eclipse.aether:aether-transport-file:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_transport_file__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-transport-file/1.1.0/aether-transport-file-1.1.0.jar"],
        downloaded_file_path = "aether-transport-file-1.1.0.jar",
        sha256 = "e519cd8726d282c03999fb591dbd811eb96b00068ee6c7984035ee98b7f64b91",
    )

    # from org.eclipse.aether:aether-transport-http:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_transport_http__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-transport-http/1.1.0/aether-transport-http-1.1.0.jar"],
        downloaded_file_path = "aether-transport-http-1.1.0.jar",
        sha256 = "9356e876bca03730e8048048a19cc83d9d84ff3ab07c13bfc555023674a3524c",
    )

    # from org.eclipse.aether:aether-transport-wagon:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_transport_wagon__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-transport-wagon/1.1.0/aether-transport-wagon-1.1.0.jar"],
        downloaded_file_path = "aether-transport-wagon-1.1.0.jar",
        sha256 = "c915ea61e451e4137879706f8b79d7d34f8c9ef140cf0e1f09bd8a54a11297f2",
    )

    # from org.eclipse.aether:aether-util:1.1.0
    http_file(
        name = "org_eclipse_aether__aether_util__1_1_0",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar"],
        downloaded_file_path = "aether-util-1.1.0.jar",
        sha256 = "556f083dd35fe7f430ac4a7705784191e39df6df89abc31b30cb538f53828d62",
    )

    # from org.eclipse.sisu:org.eclipse.sisu.inject:0.3.4
    http_file(
        name = "org_eclipse_sisu__org_eclipse_sisu_inject__0_3_4",
        urls = ["https://repo1.maven.org/maven2/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar"],
        downloaded_file_path = "org.eclipse.sisu.inject-0.3.4.jar",
        sha256 = "8c0e6aa7f35593016f2c5e78b604b57f023cdaca3561fe2fe36f2b5dbbae1d16",
    )

    # from org.hamcrest:hamcrest-core:1.3
    http_file(
        name = "org_hamcrest__hamcrest_core__1_3",
        urls = ["https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar"],
        downloaded_file_path = "hamcrest-core-1.3.jar",
        sha256 = "66fdef91e9739348df7a096aa384a5685f4e875584cce89386a7a47251c4d8e9",
    )

    # from org.mockito:mockito-core:2.23.4
    http_file(
        name = "org_mockito__mockito_core__2_23_4",
        urls = ["https://repo1.maven.org/maven2/org/mockito/mockito-core/2.23.4/mockito-core-2.23.4.jar"],
        downloaded_file_path = "mockito-core-2.23.4.jar",
        sha256 = "d77e018b6bc211d78ddcec54bc508732c4677b9a9eb9103793be85441b20bc5d",
    )

    # from org.objenesis:objenesis:2.6
    http_file(
        name = "org_objenesis__objenesis__2_6",
        urls = ["https://repo1.maven.org/maven2/org/objenesis/objenesis/2.6/objenesis-2.6.jar"],
        downloaded_file_path = "objenesis-2.6.jar",
        sha256 = "5e168368fbc250af3c79aa5fef0c3467a2d64e5a7bd74005f25d8399aeb0708d",
    )

    # from org.slf4j:jcl-over-slf4j:1.6.2
    http_file(
        name = "org_slf4j__jcl_over_slf4j__1_6_2",
        urls = ["https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.6.2/jcl-over-slf4j-1.6.2.jar"],
        downloaded_file_path = "jcl-over-slf4j-1.6.2.jar",
        sha256 = "ff95d8cbe80a47f23ba1cbb099b032e98721442f431852db6cf09303816d4b2c",
    )

    # from org.slf4j:slf4j-api:1.7.25
    http_file(
        name = "org_slf4j__slf4j_api__1_7_25",
        urls = ["https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar"],
        downloaded_file_path = "slf4j-api-1.7.25.jar",
        sha256 = "18c4a0095d5c1da6b817592e767bb23d29dd2f560ad74df75ff3961dbde25b79",
    )

    # from org.slf4j:slf4j-nop:1.7.25
    http_file(
        name = "org_slf4j__slf4j_nop__1_7_25",
        urls = ["https://repo1.maven.org/maven2/org/slf4j/slf4j-nop/1.7.25/slf4j-nop-1.7.25.jar"],
        downloaded_file_path = "slf4j-nop-1.7.25.jar",
        sha256 = "6cb127138f41b5a869f9ecdd061ad17799a0e3fe7204600797154eb0432eeb12",
    )

def _no_op_missing_aar_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require aar_import rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a aar_import which was not provided. Add argument aar_import when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_jvm_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_jvm_import which was not provided. Add argument kt_jvm_import when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_jvm_lib_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_jvm_library which was not provided. Add argument kt_jvm_library when calling generate_transitive_dependency_targets."
            .format(name),
    )

def _no_op_missing_kt_android_impl(name, **kwargs):
    """
    This is a help macro for missing concrete rule implementation.

    This will be used in cases when some dependencies require Kotlin rule implementation.

    Args:
        name: A unique name for this target.
        **kwargs: Anything else. Not used.
    """

    fail(
        "Unable to create target {} since it is a kt_android_library which was not provided. Add argument kt_android_library when calling generate_transitive_dependency_targets."
            .format(name),
    )

def generate_transitive_dependency_targets(
        name = "generate_transitive_dependency_targets",
        java_library = native.java_library,
        java_plugin = native.java_plugin,
        java_import = native.java_import,
        aar_import = _no_op_missing_aar_impl,
        kt_jvm_import = _no_op_missing_kt_jvm_impl,
        kt_jvm_library = _no_op_missing_kt_jvm_lib_impl,
        kt_android_library = _no_op_missing_kt_android_impl):
    """
    Macro to set up the transitive rules.

    You can provide your own implementation of java_import, aar_import, etc. This can be used
    in cases where you need to shade (or jar_jar or jetify) your jars.

    Args:
        name: a unique name for this macro. Not needed to specify.
        java_library: rule implementation for java_library. Defaults to native.java_library.
        java_plugin: rule implementation for java_plugin. Defaults to native.java_plugin.
        java_import: rule implementation for java_import. Defaults to native.java_import.
        aar_import: rule implementation for aar_import. Required only if you have Android dependencies.
        kt_jvm_import: rule implementation for kt_jvm_import. Required only if you have Kotlin dependencies.
        kt_jvm_library: rule implementation for kt_jvm_library. Required only if you have Kotlin dependencies.
        kt_android_library: rule implementation for kt_android_library. Required only if you have Android-Kotlin dependencies.
    """

    # from com.beust:jcommander:1.72
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_beust__jcommander",
        actual = ":com_beust__jcommander__1_72",
        visibility = ["//visibility:public"],
    )

    # from com.beust:jcommander:1.72
    # This is a root requested Maven artifact.
    java_import(
        name = "com_beust__jcommander__1_72",
        jars = ["@com_beust__jcommander__1_72//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0",
            "maven_coordinates=com.beust:jcommander:1.72",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value-annotations:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value_annotations",
        actual = ":com_google_auto_value__auto_value_annotations__1_7",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value-annotations:1.7
    # This is a root requested Maven artifact.
    java_import(
        name = "com_google_auto_value__auto_value_annotations__1_7",
        jars = ["@com_google_auto_value__auto_value_annotations__1_7//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.auto.value:auto-value-annotations:1.7",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value",
        actual = ":com_google_auto_value__auto_value__1_7",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_import(
        name = "com_google_auto_value__auto_value__1_7",
        jars = ["@com_google_auto_value__auto_value__1_7//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.auto.value:auto-value:1.7",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_0",
        processor_class = "com.google.auto.value.extension.memoized.processor.MemoizedValidator",
        generates_api = 1,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_1",
        processor_class = "com.google.auto.value.processor.AutoAnnotationProcessor",
        generates_api = 1,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_2",
        processor_class = "com.google.auto.value.processor.AutoOneOfProcessor",
        generates_api = 1,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_3",
        processor_class = "com.google.auto.value.processor.AutoValueBuilderProcessor",
        generates_api = 1,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_4",
        processor_class = "com.google.auto.value.processor.AutoValueProcessor",
        generates_api = 1,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_library(
        name = "com_google_auto_value__auto_value__1_7___generates_api___processor_class_all",
        testonly = False,
        exported_plugins = [
            ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_0",
            ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_1",
            ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_2",
            ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_3",
            ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_4",
        ],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___processor_class_0",
        processor_class = "com.google.auto.value.extension.memoized.processor.MemoizedValidator",
        generates_api = 0,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___processor_class_1",
        processor_class = "com.google.auto.value.processor.AutoAnnotationProcessor",
        generates_api = 0,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___processor_class_2",
        processor_class = "com.google.auto.value.processor.AutoOneOfProcessor",
        generates_api = 0,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___processor_class_3",
        processor_class = "com.google.auto.value.processor.AutoValueBuilderProcessor",
        generates_api = 0,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_plugin(
        name = "com_google_auto_value__auto_value__1_7___processor_class_4",
        processor_class = "com.google.auto.value.processor.AutoValueProcessor",
        generates_api = 0,
        testonly = False,
        deps = [":com_google_auto_value__auto_value__1_7"],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    java_library(
        name = "com_google_auto_value__auto_value__1_7___processor_class_all",
        testonly = False,
        exported_plugins = [
            ":com_google_auto_value__auto_value__1_7___processor_class_0",
            ":com_google_auto_value__auto_value__1_7___processor_class_1",
            ":com_google_auto_value__auto_value__1_7___processor_class_2",
            ":com_google_auto_value__auto_value__1_7___processor_class_3",
            ":com_google_auto_value__auto_value__1_7___processor_class_4",
        ],
        visibility = ["//visibility:private"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_0",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_0",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_1",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_1",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_2",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_2",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_3",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_3",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_4",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_4",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___generates_api___processor_class_all",
        actual = ":com_google_auto_value__auto_value__1_7___generates_api___processor_class_all",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_0",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_0",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_1",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_1",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_2",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_2",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_3",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_3",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_4",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_4",
        visibility = ["//visibility:public"],
    )

    # from com.google.auto.value:auto-value:1.7
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_auto_value__auto_value___processor_class_all",
        actual = ":com_google_auto_value__auto_value__1_7___processor_class_all",
        visibility = ["//visibility:public"],
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    # This is a root requested Maven artifact.
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "com_google_code_findbugs__jsr305",
        actual = ":com_google_code_findbugs__jsr305__3_0_2",
        visibility = ["//visibility:public"],
    )

    # from com.google.code.findbugs:jsr305:3.0.2
    # This is a root requested Maven artifact.
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "com_google_code_findbugs__jsr305__3_0_2",
        jars = ["@com_google_code_findbugs__jsr305__3_0_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.code.findbugs:jsr305:3.0.2",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.code.gson:gson:2.8.5
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_code_gson__gson",
        actual = ":com_google_code_gson__gson__2_8_5",
        visibility = ["//visibility:public"],
    )

    # from com.google.code.gson:gson:2.8.5
    # This is a root requested Maven artifact.
    java_import(
        name = "com_google_code_gson__gson__2_8_5",
        jars = ["@com_google_code_gson__gson__2_8_5//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.code.gson:gson:2.8.5",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "com_google_errorprone__error_prone_annotations",
        actual = ":com_google_errorprone__error_prone_annotations__2_2_0",
        visibility = ["//visibility:private"],
    )

    # from com.google.errorprone:error_prone_annotations:2.2.0
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "com_google_errorprone__error_prone_annotations__2_2_0",
        jars = ["@com_google_errorprone__error_prone_annotations__2_2_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.errorprone:error_prone_annotations:2.2.0",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.guava:failureaccess:1.0.1
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "com_google_guava__failureaccess",
        actual = ":com_google_guava__failureaccess__1_0_1",
        visibility = ["//visibility:private"],
    )

    # from com.google.guava:failureaccess:1.0.1
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "com_google_guava__failureaccess__1_0_1",
        jars = ["@com_google_guava__failureaccess__1_0_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:failureaccess:1.0.1",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.guava:guava:27.0.1-jre
    # This is a root requested Maven artifact.
    native.alias(
        name = "com_google_guava__guava",
        actual = ":com_google_guava__guava__27_0_1_jre",
        visibility = ["//visibility:public"],
    )

    # from com.google.guava:guava:27.0.1-jre
    # This is a root requested Maven artifact.
    java_import(
        name = "com_google_guava__guava__27_0_1_jre",
        jars = ["@com_google_guava__guava__27_0_1_jre//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:guava:27.0.1-jre",
        ],
        licenses = ["notice"],
        deps = [
            ":com_google_code_findbugs__jsr305",
            ":com_google_errorprone__error_prone_annotations",
            ":com_google_guava__failureaccess",
            ":com_google_guava__listenablefuture",
            ":com_google_j2objc__j2objc_annotations",
            ":org_checkerframework__checker_qual",
            ":org_codehaus_mojo__animal_sniffer_annotations",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "com_google_guava__listenablefuture",
        actual = ":com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        visibility = ["//visibility:private"],
    )

    # from com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava",
        jars = ["@com_google_guava__listenablefuture__9999_0_empty_to_avoid_conflict_with_guava//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "com_google_j2objc__j2objc_annotations",
        actual = ":com_google_j2objc__j2objc_annotations__1_1",
        visibility = ["//visibility:private"],
    )

    # from com.google.j2objc:j2objc-annotations:1.1
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "com_google_j2objc__j2objc_annotations__1_1",
        jars = ["@com_google_j2objc__j2objc_annotations__1_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=com.google.j2objc:j2objc-annotations:1.1",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from commons-codec:commons-codec:1.11
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    native.alias(
        name = "commons_codec__commons_codec",
        actual = ":commons_codec__commons_codec__1_11",
        visibility = ["//visibility:private"],
    )

    # from commons-codec:commons-codec:1.11
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    java_import(
        name = "commons_codec__commons_codec__1_11",
        jars = ["@commons_codec__commons_codec__1_11//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=commons-codec:commons-codec:1.11",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from commons-logging:commons-logging:1.2
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    native.alias(
        name = "commons_logging__commons_logging",
        actual = ":commons_logging__commons_logging__1_2",
        visibility = ["//visibility:private"],
    )

    # from commons-logging:commons-logging:1.2
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    java_import(
        name = "commons_logging__commons_logging__1_2",
        jars = ["@commons_logging__commons_logging__1_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=commons-logging:commons-logging:1.2",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from javax.inject:javax.inject:1
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "javax_inject__javax_inject",
        actual = ":javax_inject__javax_inject__1",
        visibility = ["//visibility:private"],
    )

    # from javax.inject:javax.inject:1
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "javax_inject__javax_inject__1",
        jars = ["@javax_inject__javax_inject__1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=javax.inject:javax.inject:1",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from junit:junit:4.12
    # This is a root requested Maven artifact.
    native.alias(
        name = "junit__junit",
        actual = ":junit__junit__4_12",
        visibility = ["//visibility:public"],
    )

    # from junit:junit:4.12
    # This is a root requested Maven artifact.
    java_import(
        name = "junit__junit__4_12",
        jars = ["@junit__junit__4_12//file"],
        testonly = True,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=junit:junit:4.12",
        ],
        licenses = ["reciprocal"],
        deps = [":org_hamcrest__hamcrest_core"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from net.bytebuddy:byte-buddy-agent:1.9.3
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    native.alias(
        name = "net_bytebuddy__byte_buddy_agent",
        actual = ":net_bytebuddy__byte_buddy_agent__1_9_3",
        visibility = ["//visibility:private"],
    )

    # from net.bytebuddy:byte-buddy-agent:1.9.3
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    java_import(
        name = "net_bytebuddy__byte_buddy_agent__1_9_3",
        jars = ["@net_bytebuddy__byte_buddy_agent__1_9_3//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=net.bytebuddy:byte-buddy-agent:1.9.3",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from net.bytebuddy:byte-buddy:1.9.3
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    native.alias(
        name = "net_bytebuddy__byte_buddy",
        actual = ":net_bytebuddy__byte_buddy__1_9_3",
        visibility = ["//visibility:private"],
    )

    # from net.bytebuddy:byte-buddy:1.9.3
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    java_import(
        name = "net_bytebuddy__byte_buddy__1_9_3",
        jars = ["@net_bytebuddy__byte_buddy__1_9_3//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=net.bytebuddy:byte-buddy:1.9.3",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.commons:commons-lang3:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-artifact:3.8.1'.
    native.alias(
        name = "org_apache_commons__commons_lang3",
        actual = ":org_apache_commons__commons_lang3__3_8_1",
        visibility = ["//visibility:public"],
    )

    # from org.apache.commons:commons-lang3:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-artifact:3.8.1'.
    java_import(
        name = "org_apache_commons__commons_lang3__3_8_1",
        jars = ["@org_apache_commons__commons_lang3__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.commons:commons-lang3:3.8.1",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.httpcomponents:httpclient:4.5.13
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    native.alias(
        name = "org_apache_httpcomponents__httpclient",
        actual = ":org_apache_httpcomponents__httpclient__4_5_13",
        visibility = ["//visibility:public"],
    )

    # from org.apache.httpcomponents:httpclient:4.5.13
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    java_import(
        name = "org_apache_httpcomponents__httpclient__4_5_13",
        jars = ["@org_apache_httpcomponents__httpclient__4_5_13//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.httpcomponents:httpclient:4.5.13",
        ],
        licenses = ["notice"],
        deps = [
            ":commons_codec__commons_codec",
            ":commons_logging__commons_logging",
            ":org_apache_httpcomponents__httpcore",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    native.alias(
        name = "org_apache_httpcomponents__httpcore",
        actual = ":org_apache_httpcomponents__httpcore__4_4_13",
        visibility = ["//visibility:private"],
    )

    # from org.apache.httpcomponents:httpcore:4.4.13
    # This is a dependency of 'org.apache.httpcomponents:httpclient:4.5.13'.
    java_import(
        name = "org_apache_httpcomponents__httpcore__4_4_13",
        jars = ["@org_apache_httpcomponents__httpcore__4_4_13//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.httpcomponents:httpcore:4.4.13",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    native.alias(
        name = "org_apache_maven_wagon__wagon_provider_api",
        actual = ":org_apache_maven_wagon__wagon_provider_api__1_0",
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven.wagon:wagon-provider-api:1.0
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    java_import(
        name = "org_apache_maven_wagon__wagon_provider_api__1_0",
        jars = ["@org_apache_maven_wagon__wagon_provider_api__1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven.wagon:wagon-provider-api:1.0",
        ],
        licenses = ["notice"],
        deps = [":org_codehaus_plexus__plexus_utils"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-aether-provider:3.3.9
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_apache_maven__maven_aether_provider",
        actual = ":org_apache_maven__maven_aether_provider__3_3_9",
        visibility = ["//visibility:public"],
    )

    # from org.apache.maven:maven-aether-provider:3.3.9
    # This is a root requested Maven artifact.
    java_import(
        name = "org_apache_maven__maven_aether_provider__3_3_9",
        jars = ["@org_apache_maven__maven_aether_provider__3_3_9//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-aether-provider:3.3.9",
        ],
        licenses = ["notice"],
        deps = [
            ":org_apache_commons__commons_lang3",
            ":org_apache_maven__maven_model",
            ":org_apache_maven__maven_model_builder",
            ":org_apache_maven__maven_repository_metadata",
            ":org_codehaus_plexus__plexus_component_annotations",
            ":org_codehaus_plexus__plexus_utils",
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_impl",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-artifact:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "org_apache_maven__maven_artifact",
        actual = ":org_apache_maven__maven_artifact__3_8_1",
        visibility = ["//visibility:public"],
    )

    # from org.apache.maven:maven-artifact:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "org_apache_maven__maven_artifact__3_8_1",
        jars = ["@org_apache_maven__maven_artifact__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-artifact:3.8.1",
        ],
        licenses = ["notice"],
        deps = [
            ":org_apache_commons__commons_lang3",
            ":org_codehaus_plexus__plexus_utils",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-builder-support:3.8.1
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "org_apache_maven__maven_builder_support",
        actual = ":org_apache_maven__maven_builder_support__3_8_1",
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-builder-support:3.8.1
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "org_apache_maven__maven_builder_support__3_8_1",
        jars = ["@org_apache_maven__maven_builder_support__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-builder-support:3.8.1",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-model-builder:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    native.alias(
        name = "org_apache_maven__maven_model_builder",
        actual = ":org_apache_maven__maven_model_builder__3_8_1",
        visibility = ["//visibility:public"],
    )

    # from org.apache.maven:maven-model-builder:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    java_import(
        name = "org_apache_maven__maven_model_builder__3_8_1",
        jars = ["@org_apache_maven__maven_model_builder__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-model-builder:3.8.1",
        ],
        licenses = ["notice"],
        deps = [
            ":javax_inject__javax_inject",
            ":org_apache_maven__maven_artifact",
            ":org_apache_maven__maven_builder_support",
            ":org_apache_maven__maven_model",
            ":org_codehaus_plexus__plexus_interpolation",
            ":org_codehaus_plexus__plexus_utils",
            ":org_eclipse_sisu__org_eclipse_sisu_inject",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-model:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "org_apache_maven__maven_model",
        actual = ":org_apache_maven__maven_model__3_8_1",
        visibility = ["//visibility:public"],
    )

    # from org.apache.maven:maven-model:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "org_apache_maven__maven_model__3_8_1",
        jars = ["@org_apache_maven__maven_model__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-model:3.8.1",
        ],
        licenses = ["notice"],
        deps = [":org_codehaus_plexus__plexus_utils"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.apache.maven:maven-repository-metadata:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    native.alias(
        name = "org_apache_maven__maven_repository_metadata",
        actual = ":org_apache_maven__maven_repository_metadata__3_8_1",
        visibility = ["//visibility:public"],
    )

    # from org.apache.maven:maven-repository-metadata:3.8.1
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    java_import(
        name = "org_apache_maven__maven_repository_metadata__3_8_1",
        jars = ["@org_apache_maven__maven_repository_metadata__3_8_1//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=https://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.apache.maven:maven-repository-metadata:3.8.1",
        ],
        licenses = ["notice"],
        deps = [":org_codehaus_plexus__plexus_utils"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.checkerframework:checker-qual:2.5.2
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "org_checkerframework__checker_qual",
        actual = ":org_checkerframework__checker_qual__2_5_2",
        visibility = ["//visibility:private"],
    )

    # from org.checkerframework:checker-qual:2.5.2
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "org_checkerframework__checker_qual__2_5_2",
        jars = ["@org_checkerframework__checker_qual__2_5_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=The MIT License",
            "mabel_license_url=http://opensource.org/licenses/MIT",
            "maven_coordinates=org.checkerframework:checker-qual:2.5.2",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    native.alias(
        name = "org_codehaus_mojo__animal_sniffer_annotations",
        actual = ":org_codehaus_mojo__animal_sniffer_annotations__1_17",
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.mojo:animal-sniffer-annotations:1.17
    # This is a dependency of 'com.google.guava:guava:27.0.1-jre'.
    java_import(
        name = "org_codehaus_mojo__animal_sniffer_annotations__1_17",
        jars = ["@org_codehaus_mojo__animal_sniffer_annotations__1_17//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=MIT license",
            "mabel_license_url=http://www.opensource.org/licenses/mit-license.php",
            "maven_coordinates=org.codehaus.mojo:animal-sniffer-annotations:1.17",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.plexus:plexus-component-annotations:1.6
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    native.alias(
        name = "org_codehaus_plexus__plexus_component_annotations",
        actual = ":org_codehaus_plexus__plexus_component_annotations__1_6",
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.plexus:plexus-component-annotations:1.6
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    java_import(
        name = "org_codehaus_plexus__plexus_component_annotations__1_6",
        jars = ["@org_codehaus_plexus__plexus_component_annotations__1_6//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=The Apache Software License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.codehaus.plexus:plexus-component-annotations:1.6",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.plexus:plexus-interpolation:1.26
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "org_codehaus_plexus__plexus_interpolation",
        actual = ":org_codehaus_plexus__plexus_interpolation__1_26",
        visibility = ["//visibility:public"],
    )

    # from org.codehaus.plexus:plexus-interpolation:1.26
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "org_codehaus_plexus__plexus_interpolation__1_26",
        jars = ["@org_codehaus_plexus__plexus_interpolation__1_26//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.codehaus.plexus:plexus-interpolation:1.26",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.codehaus.plexus:plexus-utils:3.3.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven.wagon:wagon-provider-api:1.0'.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-artifact:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-model:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-repository-metadata:3.8.1'.
    native.alias(
        name = "org_codehaus_plexus__plexus_utils",
        actual = ":org_codehaus_plexus__plexus_utils__3_3_0",
        visibility = ["//visibility:public"],
    )

    # from org.codehaus.plexus:plexus-utils:3.3.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven.wagon:wagon-provider-api:1.0'.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.apache.maven:maven-artifact:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-model:3.8.1'.
    # This is a dependency of 'org.apache.maven:maven-repository-metadata:3.8.1'.
    java_import(
        name = "org_codehaus_plexus__plexus_utils__3_3_0",
        jars = ["@org_codehaus_plexus__plexus_utils__3_3_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache License, Version 2.0",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.codehaus.plexus:plexus-utils:3.3.0",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-api:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-spi:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-util:1.1.0'.
    native.alias(
        name = "org_eclipse_aether__aether_api",
        actual = ":org_eclipse_aether__aether_api__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-api:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-spi:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-util:1.1.0'.
    java_import(
        name = "org_eclipse_aether__aether_api__1_1_0",
        jars = ["@org_eclipse_aether__aether_api__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-api:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-connector-basic:1.1.0
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_eclipse_aether__aether_connector_basic",
        actual = ":org_eclipse_aether__aether_connector_basic__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-connector-basic:1.1.0
    # This is a root requested Maven artifact.
    java_import(
        name = "org_eclipse_aether__aether_connector_basic__1_1_0",
        jars = ["@org_eclipse_aether__aether_connector_basic__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-connector-basic:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-impl:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    native.alias(
        name = "org_eclipse_aether__aether_impl",
        actual = ":org_eclipse_aether__aether_impl__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-impl:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    java_import(
        name = "org_eclipse_aether__aether_impl__1_1_0",
        jars = ["@org_eclipse_aether__aether_impl__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-impl:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-spi:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    native.alias(
        name = "org_eclipse_aether__aether_spi",
        actual = ":org_eclipse_aether__aether_spi__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-spi:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    java_import(
        name = "org_eclipse_aether__aether_spi__1_1_0",
        jars = ["@org_eclipse_aether__aether_spi__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-spi:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [":org_eclipse_aether__aether_api"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-transport-classpath:1.1.0
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_eclipse_aether__aether_transport_classpath",
        actual = ":org_eclipse_aether__aether_transport_classpath__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-transport-classpath:1.1.0
    # This is a root requested Maven artifact.
    java_import(
        name = "org_eclipse_aether__aether_transport_classpath__1_1_0",
        jars = ["@org_eclipse_aether__aether_transport_classpath__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-transport-classpath:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-transport-file:1.1.0
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_eclipse_aether__aether_transport_file",
        actual = ":org_eclipse_aether__aether_transport_file__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-transport-file:1.1.0
    # This is a root requested Maven artifact.
    java_import(
        name = "org_eclipse_aether__aether_transport_file__1_1_0",
        jars = ["@org_eclipse_aether__aether_transport_file__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-transport-file:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-transport-http:1.1.0
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_eclipse_aether__aether_transport_http",
        actual = ":org_eclipse_aether__aether_transport_http__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-transport-http:1.1.0
    # This is a root requested Maven artifact.
    java_import(
        name = "org_eclipse_aether__aether_transport_http__1_1_0",
        jars = ["@org_eclipse_aether__aether_transport_http__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-transport-http:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_apache_httpcomponents__httpclient",
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
            ":org_slf4j__jcl_over_slf4j",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-transport-wagon:1.1.0
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_eclipse_aether__aether_transport_wagon",
        actual = ":org_eclipse_aether__aether_transport_wagon__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-transport-wagon:1.1.0
    # This is a root requested Maven artifact.
    java_import(
        name = "org_eclipse_aether__aether_transport_wagon__1_1_0",
        jars = ["@org_eclipse_aether__aether_transport_wagon__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-transport-wagon:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [
            ":org_apache_maven_wagon__wagon_provider_api",
            ":org_eclipse_aether__aether_api",
            ":org_eclipse_aether__aether_spi",
            ":org_eclipse_aether__aether_util",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.aether:aether-util:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    native.alias(
        name = "org_eclipse_aether__aether_util",
        actual = ":org_eclipse_aether__aether_util__1_1_0",
        visibility = ["//visibility:public"],
    )

    # from org.eclipse.aether:aether-util:1.1.0
    # This is a root requested Maven artifact.
    # This is a dependency of 'org.apache.maven:maven-aether-provider:3.3.9'.
    # This is a dependency of 'org.eclipse.aether:aether-connector-basic:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-impl:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-classpath:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-file:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    # This is a dependency of 'org.eclipse.aether:aether-transport-wagon:1.1.0'.
    java_import(
        name = "org_eclipse_aether__aether_util__1_1_0",
        jars = ["@org_eclipse_aether__aether_util__1_1_0//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.aether:aether-util:1.1.0",
        ],
        licenses = ["reciprocal"],
        deps = [":org_eclipse_aether__aether_api"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.sisu:org.eclipse.sisu.inject:0.3.4
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    native.alias(
        name = "org_eclipse_sisu__org_eclipse_sisu_inject",
        actual = ":org_eclipse_sisu__org_eclipse_sisu_inject__0_3_4",
        visibility = ["//visibility:private"],
    )

    # from org.eclipse.sisu:org.eclipse.sisu.inject:0.3.4
    # This is a dependency of 'org.apache.maven:maven-model-builder:3.8.1'.
    java_import(
        name = "org_eclipse_sisu__org_eclipse_sisu_inject__0_3_4",
        jars = ["@org_eclipse_sisu__org_eclipse_sisu_inject__0_3_4//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Eclipse",
            "mabel_license_name=Eclipse Public License, Version 1.0",
            "mabel_license_url=http://www.eclipse.org/legal/epl-v10.html",
            "maven_coordinates=org.eclipse.sisu:org.eclipse.sisu.inject:0.3.4",
        ],
        licenses = ["reciprocal"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.hamcrest:hamcrest-core:1.3
    # This is a dependency of 'junit:junit:4.12'.
    native.alias(
        name = "org_hamcrest__hamcrest_core",
        actual = ":org_hamcrest__hamcrest_core__1_3",
        visibility = ["//visibility:private"],
    )

    # from org.hamcrest:hamcrest-core:1.3
    # This is a dependency of 'junit:junit:4.12'.
    java_import(
        name = "org_hamcrest__hamcrest_core__1_3",
        jars = ["@org_hamcrest__hamcrest_core__1_3//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=BSD",
            "mabel_license_name=New BSD License",
            "mabel_license_url=http://www.opensource.org/licenses/bsd-license.php",
            "maven_coordinates=org.hamcrest:hamcrest-core:1.3",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.mockito:mockito-core:2.23.4
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_mockito__mockito_core",
        actual = ":org_mockito__mockito_core__2_23_4",
        visibility = ["//visibility:public"],
    )

    # from org.mockito:mockito-core:2.23.4
    # This is a root requested Maven artifact.
    java_import(
        name = "org_mockito__mockito_core__2_23_4",
        jars = ["@org_mockito__mockito_core__2_23_4//file"],
        testonly = True,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=The MIT License",
            "mabel_license_url=https://github.com/mockito/mockito/blob/master/LICENSE",
            "maven_coordinates=org.mockito:mockito-core:2.23.4",
        ],
        licenses = ["notice"],
        deps = [
            ":net_bytebuddy__byte_buddy",
            ":net_bytebuddy__byte_buddy_agent",
            ":org_objenesis__objenesis",
        ],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.objenesis:objenesis:2.6
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    native.alias(
        name = "org_objenesis__objenesis",
        actual = ":org_objenesis__objenesis__2_6",
        visibility = ["//visibility:private"],
    )

    # from org.objenesis:objenesis:2.6
    # This is a dependency of 'org.mockito:mockito-core:2.23.4'.
    java_import(
        name = "org_objenesis__objenesis__2_6",
        jars = ["@org_objenesis__objenesis__2_6//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=Apache",
            "mabel_license_name=Apache 2",
            "mabel_license_url=http://www.apache.org/licenses/LICENSE-2.0.txt",
            "maven_coordinates=org.objenesis:objenesis:2.6",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.slf4j:jcl-over-slf4j:1.6.2
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    native.alias(
        name = "org_slf4j__jcl_over_slf4j",
        actual = ":org_slf4j__jcl_over_slf4j__1_6_2",
        visibility = ["//visibility:private"],
    )

    # from org.slf4j:jcl-over-slf4j:1.6.2
    # This is a dependency of 'org.eclipse.aether:aether-transport-http:1.1.0'.
    java_import(
        name = "org_slf4j__jcl_over_slf4j__1_6_2",
        jars = ["@org_slf4j__jcl_over_slf4j__1_6_2//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=MIT License",
            "mabel_license_url=http://www.opensource.org/licenses/mit-license.php",
            "maven_coordinates=org.slf4j:jcl-over-slf4j:1.6.2",
        ],
        licenses = ["notice"],
        deps = [":org_slf4j__slf4j_api"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.slf4j:slf4j-api:1.7.25
    # This is a dependency of 'org.slf4j:jcl-over-slf4j:1.6.2'.
    # This is a dependency of 'org.slf4j:slf4j-nop:1.7.25'.
    native.alias(
        name = "org_slf4j__slf4j_api",
        actual = ":org_slf4j__slf4j_api__1_7_25",
        visibility = ["//visibility:private"],
    )

    # from org.slf4j:slf4j-api:1.7.25
    # This is a dependency of 'org.slf4j:jcl-over-slf4j:1.6.2'.
    # This is a dependency of 'org.slf4j:slf4j-nop:1.7.25'.
    java_import(
        name = "org_slf4j__slf4j_api__1_7_25",
        jars = ["@org_slf4j__slf4j_api__1_7_25//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=MIT License",
            "mabel_license_url=http://www.opensource.org/licenses/mit-license.php",
            "maven_coordinates=org.slf4j:slf4j-api:1.7.25",
        ],
        licenses = ["notice"],
        deps = [],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )

    # from org.slf4j:slf4j-nop:1.7.25
    # This is a root requested Maven artifact.
    native.alias(
        name = "org_slf4j__slf4j_nop",
        actual = ":org_slf4j__slf4j_nop__1_7_25",
        visibility = ["//visibility:public"],
    )

    # from org.slf4j:slf4j-nop:1.7.25
    # This is a root requested Maven artifact.
    java_import(
        name = "org_slf4j__slf4j_nop__1_7_25",
        jars = ["@org_slf4j__slf4j_nop__1_7_25//file"],
        testonly = False,
        tags = [
            "mabel_license_detected_type=MIT",
            "mabel_license_name=MIT License",
            "mabel_license_url=http://www.opensource.org/licenses/mit-license.php",
            "maven_coordinates=org.slf4j:slf4j-nop:1.7.25",
        ],
        licenses = ["notice"],
        deps = [":org_slf4j__slf4j_api"],
        runtime_deps = [],
        visibility = ["//visibility:private"],
    )
