load("@aspect_rules_lint//format:defs.bzl", "format_multirun")

# `run`ing this target will format the entire repo
format_multirun(
    name = "format",
    java = "//tools:java-format",
    starlark = "@buildifier_prebuilt//:buildifier",
    visibility = ["//visibility:public"],
    yaml = "//tools:yamlfmt_runner",
)
