"""
Required macros for creating repository-rules and third-party Maven dependencies.

Auto-generated by https://github.com/menny/mabel
"""

# Loading a drop-in replacement for native.http_file
load('@bazel_tools//tools/build_defs/repo:http.bzl', 'http_file')

def generate_workspace_rules():
    """
    Repository rules macro to be run in the WORKSPACE file.
    """
    # from androidx.activity:activity:1.0.0-alpha02
    http_file(name = 'androidx_activity__activity__1_0_0_alpha02',
        urls = ['https://maven.google.com/androidx/activity/activity/1.0.0-alpha02/activity-1.0.0-alpha02.aar'],
        downloaded_file_path = 'activity-1.0.0-alpha02.aar',
    )

    # from androidx.annotation:annotation:1.0.0
    http_file(name = 'androidx_annotation__annotation__1_0_0',
        urls = ['https://maven.google.com/androidx/annotation/annotation/1.0.0/annotation-1.0.0.jar'],
        downloaded_file_path = 'annotation-1.0.0.jar',
    )

    # from androidx.appcompat:appcompat:1.0.2
    http_file(name = 'androidx_appcompat__appcompat__1_0_2',
        urls = ['https://maven.google.com/androidx/appcompat/appcompat/1.0.2/appcompat-1.0.2.aar'],
        downloaded_file_path = 'appcompat-1.0.2.aar',
    )

    # from androidx.arch.core:core-common:2.0.0
    http_file(name = 'androidx_arch_core__core_common__2_0_0',
        urls = ['https://maven.google.com/androidx/arch/core/core-common/2.0.0/core-common-2.0.0.jar'],
        downloaded_file_path = 'core-common-2.0.0.jar',
    )

    # from androidx.arch.core:core-runtime:2.0.0
    http_file(name = 'androidx_arch_core__core_runtime__2_0_0',
        urls = ['https://maven.google.com/androidx/arch/core/core-runtime/2.0.0/core-runtime-2.0.0.aar'],
        downloaded_file_path = 'core-runtime-2.0.0.aar',
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    http_file(name = 'androidx_asynclayoutinflater__asynclayoutinflater__1_0_0',
        urls = ['https://maven.google.com/androidx/asynclayoutinflater/asynclayoutinflater/1.0.0/asynclayoutinflater-1.0.0.aar'],
        downloaded_file_path = 'asynclayoutinflater-1.0.0.aar',
    )

    # from androidx.collection:collection:1.0.0
    http_file(name = 'androidx_collection__collection__1_0_0',
        urls = ['https://maven.google.com/androidx/collection/collection/1.0.0/collection-1.0.0.jar'],
        downloaded_file_path = 'collection-1.0.0.jar',
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    http_file(name = 'androidx_coordinatorlayout__coordinatorlayout__1_0_0',
        urls = ['https://maven.google.com/androidx/coordinatorlayout/coordinatorlayout/1.0.0/coordinatorlayout-1.0.0.aar'],
        downloaded_file_path = 'coordinatorlayout-1.0.0.aar',
    )

    # from androidx.core:core:1.1.0-alpha01
    http_file(name = 'androidx_core__core__1_1_0_alpha01',
        urls = ['https://maven.google.com/androidx/core/core/1.1.0-alpha01/core-1.1.0-alpha01.aar'],
        downloaded_file_path = 'core-1.1.0-alpha01.aar',
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    http_file(name = 'androidx_cursoradapter__cursoradapter__1_0_0',
        urls = ['https://maven.google.com/androidx/cursoradapter/cursoradapter/1.0.0/cursoradapter-1.0.0.aar'],
        downloaded_file_path = 'cursoradapter-1.0.0.aar',
    )

    # from androidx.customview:customview:1.0.0
    http_file(name = 'androidx_customview__customview__1_0_0',
        urls = ['https://maven.google.com/androidx/customview/customview/1.0.0/customview-1.0.0.aar'],
        downloaded_file_path = 'customview-1.0.0.aar',
    )

    # from androidx.documentfile:documentfile:1.0.0
    http_file(name = 'androidx_documentfile__documentfile__1_0_0',
        urls = ['https://maven.google.com/androidx/documentfile/documentfile/1.0.0/documentfile-1.0.0.aar'],
        downloaded_file_path = 'documentfile-1.0.0.aar',
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    http_file(name = 'androidx_drawerlayout__drawerlayout__1_0_0',
        urls = ['https://maven.google.com/androidx/drawerlayout/drawerlayout/1.0.0/drawerlayout-1.0.0.aar'],
        downloaded_file_path = 'drawerlayout-1.0.0.aar',
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    http_file(name = 'androidx_fragment__fragment__1_1_0_alpha02',
        urls = ['https://maven.google.com/androidx/fragment/fragment/1.1.0-alpha02/fragment-1.1.0-alpha02.aar'],
        downloaded_file_path = 'fragment-1.1.0-alpha02.aar',
    )

    # from androidx.interpolator:interpolator:1.0.0
    http_file(name = 'androidx_interpolator__interpolator__1_0_0',
        urls = ['https://maven.google.com/androidx/interpolator/interpolator/1.0.0/interpolator-1.0.0.aar'],
        downloaded_file_path = 'interpolator-1.0.0.aar',
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    http_file(name = 'androidx_legacy__legacy_support_core_ui__1_0_0',
        urls = ['https://maven.google.com/androidx/legacy/legacy-support-core-ui/1.0.0/legacy-support-core-ui-1.0.0.aar'],
        downloaded_file_path = 'legacy-support-core-ui-1.0.0.aar',
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    http_file(name = 'androidx_legacy__legacy_support_core_utils__1_0_0',
        urls = ['https://maven.google.com/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.aar'],
        downloaded_file_path = 'legacy-support-core-utils-1.0.0.aar',
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    http_file(name = 'androidx_lifecycle__lifecycle_common__2_0_0',
        urls = ['https://maven.google.com/androidx/lifecycle/lifecycle-common/2.0.0/lifecycle-common-2.0.0.jar'],
        downloaded_file_path = 'lifecycle-common-2.0.0.jar',
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    http_file(name = 'androidx_lifecycle__lifecycle_livedata_core__2_0_0',
        urls = ['https://maven.google.com/androidx/lifecycle/lifecycle-livedata-core/2.0.0/lifecycle-livedata-core-2.0.0.aar'],
        downloaded_file_path = 'lifecycle-livedata-core-2.0.0.aar',
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    http_file(name = 'androidx_lifecycle__lifecycle_livedata__2_0_0',
        urls = ['https://maven.google.com/androidx/lifecycle/lifecycle-livedata/2.0.0/lifecycle-livedata-2.0.0.aar'],
        downloaded_file_path = 'lifecycle-livedata-2.0.0.aar',
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    http_file(name = 'androidx_lifecycle__lifecycle_runtime__2_0_0',
        urls = ['https://maven.google.com/androidx/lifecycle/lifecycle-runtime/2.0.0/lifecycle-runtime-2.0.0.aar'],
        downloaded_file_path = 'lifecycle-runtime-2.0.0.aar',
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    http_file(name = 'androidx_lifecycle__lifecycle_viewmodel__2_0_0',
        urls = ['https://maven.google.com/androidx/lifecycle/lifecycle-viewmodel/2.0.0/lifecycle-viewmodel-2.0.0.aar'],
        downloaded_file_path = 'lifecycle-viewmodel-2.0.0.aar',
    )

    # from androidx.loader:loader:1.0.0
    http_file(name = 'androidx_loader__loader__1_0_0',
        urls = ['https://maven.google.com/androidx/loader/loader/1.0.0/loader-1.0.0.aar'],
        downloaded_file_path = 'loader-1.0.0.aar',
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    http_file(name = 'androidx_localbroadcastmanager__localbroadcastmanager__1_0_0',
        urls = ['https://maven.google.com/androidx/localbroadcastmanager/localbroadcastmanager/1.0.0/localbroadcastmanager-1.0.0.aar'],
        downloaded_file_path = 'localbroadcastmanager-1.0.0.aar',
    )

    # from androidx.print:print:1.0.0
    http_file(name = 'androidx_print__print__1_0_0',
        urls = ['https://maven.google.com/androidx/print/print/1.0.0/print-1.0.0.aar'],
        downloaded_file_path = 'print-1.0.0.aar',
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    http_file(name = 'androidx_slidingpanelayout__slidingpanelayout__1_0_0',
        urls = ['https://maven.google.com/androidx/slidingpanelayout/slidingpanelayout/1.0.0/slidingpanelayout-1.0.0.aar'],
        downloaded_file_path = 'slidingpanelayout-1.0.0.aar',
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    http_file(name = 'androidx_swiperefreshlayout__swiperefreshlayout__1_0_0',
        urls = ['https://maven.google.com/androidx/swiperefreshlayout/swiperefreshlayout/1.0.0/swiperefreshlayout-1.0.0.aar'],
        downloaded_file_path = 'swiperefreshlayout-1.0.0.aar',
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    http_file(name = 'androidx_vectordrawable__vectordrawable_animated__1_0_0',
        urls = ['https://maven.google.com/androidx/vectordrawable/vectordrawable-animated/1.0.0/vectordrawable-animated-1.0.0.aar'],
        downloaded_file_path = 'vectordrawable-animated-1.0.0.aar',
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    http_file(name = 'androidx_vectordrawable__vectordrawable__1_0_1',
        urls = ['https://maven.google.com/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.aar'],
        downloaded_file_path = 'vectordrawable-1.0.1.aar',
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    http_file(name = 'androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01',
        urls = ['https://maven.google.com/androidx/versionedparcelable/versionedparcelable/1.1.0-alpha01/versionedparcelable-1.1.0-alpha01.aar'],
        downloaded_file_path = 'versionedparcelable-1.1.0-alpha01.aar',
    )

    # from androidx.viewpager:viewpager:1.0.0
    http_file(name = 'androidx_viewpager__viewpager__1_0_0',
        urls = ['https://maven.google.com/androidx/viewpager/viewpager/1.0.0/viewpager-1.0.0.aar'],
        downloaded_file_path = 'viewpager-1.0.0.aar',
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    http_file(name = 'com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406',
        urls = ['https://jitpack.io/com/github/menny/Chauffeur/lib/90e703256785b7baf9cd37370b62b1d7d3830406/lib-90e703256785b7baf9cd37370b62b1d7d3830406.aar'],
        downloaded_file_path = 'lib-90e703256785b7baf9cd37370b62b1d7d3830406.aar',
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    http_file(name = 'com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406',
        urls = ['https://jitpack.io/com/github/menny/Chauffeur/permissions/90e703256785b7baf9cd37370b62b1d7d3830406/permissions-90e703256785b7baf9cd37370b62b1d7d3830406.aar'],
        downloaded_file_path = 'permissions-90e703256785b7baf9cd37370b62b1d7d3830406.aar',
    )



def kotlin_jar_support(name, deps, exports, runtime_deps, jar, java_import_impl, kt_jvm_import=None, kt_jvm_library=None):
    """
    This is a help macro to handle Kotlin rules.

    Transitive rules macro to be run in the BUILD.bazel file.
    If you use kt_* rules, you MUST provide the correct rule implementation when call this macro, if you decide
    not to provide those implementations we'll try to use java_* rules.
    
    Args:
        name: A unique name for this target.
        deps: The list of other libraries to be linked in to the target.
        exports: Targets to make available to users of this rule.
        runtime_deps: Libraries to make available to the final binary or test at runtime only.
        jar: The JAR file provided to Java targets that depend on this target.
        java_import_impl: rule implementation for java_import.
        kt_jvm_import: rule implementation for kt_jvm_import. Can be None.
        kt_jvm_library: rule implementation for kt_jvm_library. Can be None.
    """
    #In case the developer did not provide a kt_* impl, we'll try to use java_*, should work
    if kt_jvm_import == None:
        java_import_impl(name = name,
            jars = [jar],
            deps = deps,
            exports = exports,
            runtime_deps = runtime_deps,
        )
    else:
        kt_jvm_import(name = '{}_kotlin_jar'.format(name),
            jars = [jar],
        )
        kt_jvm_library(name = name,
            deps = deps + [':{}_kotlin_jar'.format(name)],
            exports = exports + [':{}_kotlin_jar'.format(name)],
            runtime_deps = runtime_deps,
        )

def generate_transitive_dependency_targets(java_import_impl=native.java_import, aar_import_impl=native.aar_import, kt_jvm_import=None, kt_jvm_library=None):
    """
    Macro to set up the transitive rules.

    You can provide your own implementation of java_import and aar_import. This can be used
    in cases where you need to shade (or jar_jar or jetify) your jars.
    
    Args:
        java_import_impl: rule implementation for java_import.
        aar_import_impl: rule implementation for aar_import.
        kt_jvm_import: rule implementation for kt_jvm_import.
        kt_jvm_library: rule implementation for kt_jvm_library.
    """
    # from androidx.activity:activity:1.0.0-alpha02
    native.alias(name = 'androidx_activity__activity',
        actual = ':androidx_activity__activity__1_0_0_alpha02',
        visibility = ['//visibility:public'],
    )

    # from androidx.activity:activity:1.0.0-alpha02
    aar_import_impl(name = 'androidx_activity__activity__1_0_0_alpha02',
        aar = '@androidx_activity__activity__1_0_0_alpha02//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_runtime',
            ':androidx_lifecycle__lifecycle_viewmodel',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_runtime',
            ':androidx_lifecycle__lifecycle_viewmodel',
        ],
    )

    # from androidx.annotation:annotation:1.0.0
    native.alias(name = 'androidx_annotation__annotation',
        actual = ':androidx_annotation__annotation__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.annotation:annotation:1.0.0
    java_import_impl(name = 'androidx_annotation__annotation__1_0_0',
        jars = ['@androidx_annotation__annotation__1_0_0//file'],
        tags = ['maven_coordinates=androidx.annotation:annotation:1.0.0'],
        licenses = ['notice'],
        deps = [],
        exports = [],
        runtime_deps = [],
    )

    # from androidx.appcompat:appcompat:1.0.2
    native.alias(name = 'androidx_appcompat__appcompat',
        actual = ':androidx_appcompat__appcompat__1_0_2',
        visibility = ['//visibility:public'],
    )

    # from androidx.appcompat:appcompat:1.0.2
    aar_import_impl(name = 'androidx_appcompat__appcompat__1_0_2',
        aar = '@androidx_appcompat__appcompat__1_0_2//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
            ':androidx_core__core',
            ':androidx_cursoradapter__cursoradapter',
            ':androidx_fragment__fragment',
            ':androidx_legacy__legacy_support_core_utils',
            ':androidx_vectordrawable__vectordrawable',
            ':androidx_vectordrawable__vectordrawable_animated',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
            ':androidx_core__core',
            ':androidx_cursoradapter__cursoradapter',
            ':androidx_fragment__fragment',
            ':androidx_legacy__legacy_support_core_utils',
            ':androidx_vectordrawable__vectordrawable',
            ':androidx_vectordrawable__vectordrawable_animated',
        ],
    )

    # from androidx.arch.core:core-common:2.0.0
    native.alias(name = 'androidx_arch_core__core_common',
        actual = ':androidx_arch_core__core_common__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.arch.core:core-common:2.0.0
    java_import_impl(name = 'androidx_arch_core__core_common__2_0_0',
        jars = ['@androidx_arch_core__core_common__2_0_0//file'],
        tags = ['maven_coordinates=androidx.arch.core:core-common:2.0.0'],
        licenses = ['notice'],
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
        runtime_deps = [],
    )

    # from androidx.arch.core:core-runtime:2.0.0
    native.alias(name = 'androidx_arch_core__core_runtime',
        actual = ':androidx_arch_core__core_runtime__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.arch.core:core-runtime:2.0.0
    aar_import_impl(name = 'androidx_arch_core__core_runtime__2_0_0',
        aar = '@androidx_arch_core__core_runtime__2_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_arch_core__core_common',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_arch_core__core_common',
        ],
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    native.alias(name = 'androidx_asynclayoutinflater__asynclayoutinflater',
        actual = ':androidx_asynclayoutinflater__asynclayoutinflater__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
    aar_import_impl(name = 'androidx_asynclayoutinflater__asynclayoutinflater__1_0_0',
        aar = '@androidx_asynclayoutinflater__asynclayoutinflater__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
    )

    # from androidx.collection:collection:1.0.0
    native.alias(name = 'androidx_collection__collection',
        actual = ':androidx_collection__collection__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.collection:collection:1.0.0
    java_import_impl(name = 'androidx_collection__collection__1_0_0',
        jars = ['@androidx_collection__collection__1_0_0//file'],
        tags = ['maven_coordinates=androidx.collection:collection:1.0.0'],
        licenses = ['notice'],
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
        runtime_deps = [],
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    native.alias(name = 'androidx_coordinatorlayout__coordinatorlayout',
        actual = ':androidx_coordinatorlayout__coordinatorlayout__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.coordinatorlayout:coordinatorlayout:1.0.0
    aar_import_impl(name = 'androidx_coordinatorlayout__coordinatorlayout__1_0_0',
        aar = '@androidx_coordinatorlayout__coordinatorlayout__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
    )

    # from androidx.core:core:1.1.0-alpha01
    native.alias(name = 'androidx_core__core',
        actual = ':androidx_core__core__1_1_0_alpha01',
        visibility = ['//visibility:public'],
    )

    # from androidx.core:core:1.1.0-alpha01
    aar_import_impl(name = 'androidx_core__core__1_1_0_alpha01',
        aar = '@androidx_core__core__1_1_0_alpha01//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
            ':androidx_lifecycle__lifecycle_runtime',
            ':androidx_versionedparcelable__versionedparcelable',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
            ':androidx_lifecycle__lifecycle_runtime',
            ':androidx_versionedparcelable__versionedparcelable',
        ],
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    native.alias(name = 'androidx_cursoradapter__cursoradapter',
        actual = ':androidx_cursoradapter__cursoradapter__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.cursoradapter:cursoradapter:1.0.0
    aar_import_impl(name = 'androidx_cursoradapter__cursoradapter__1_0_0',
        aar = '@androidx_cursoradapter__cursoradapter__1_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.customview:customview:1.0.0
    native.alias(name = 'androidx_customview__customview',
        actual = ':androidx_customview__customview__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.customview:customview:1.0.0
    aar_import_impl(name = 'androidx_customview__customview__1_0_0',
        aar = '@androidx_customview__customview__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
    )

    # from androidx.documentfile:documentfile:1.0.0
    native.alias(name = 'androidx_documentfile__documentfile',
        actual = ':androidx_documentfile__documentfile__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.documentfile:documentfile:1.0.0
    aar_import_impl(name = 'androidx_documentfile__documentfile__1_0_0',
        aar = '@androidx_documentfile__documentfile__1_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    native.alias(name = 'androidx_drawerlayout__drawerlayout',
        actual = ':androidx_drawerlayout__drawerlayout__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.drawerlayout:drawerlayout:1.0.0
    aar_import_impl(name = 'androidx_drawerlayout__drawerlayout__1_0_0',
        aar = '@androidx_drawerlayout__drawerlayout__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    native.alias(name = 'androidx_fragment__fragment',
        actual = ':androidx_fragment__fragment__1_1_0_alpha02',
        visibility = ['//visibility:public'],
    )

    # from androidx.fragment:fragment:1.1.0-alpha02
    aar_import_impl(name = 'androidx_fragment__fragment__1_1_0_alpha02',
        aar = '@androidx_fragment__fragment__1_1_0_alpha02//file',
        deps = [
            ':androidx_activity__activity',
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_viewmodel',
            ':androidx_loader__loader',
            ':androidx_viewpager__viewpager',
        ],
        exports = [
            ':androidx_activity__activity',
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_viewmodel',
            ':androidx_loader__loader',
            ':androidx_viewpager__viewpager',
        ],
    )

    # from androidx.interpolator:interpolator:1.0.0
    native.alias(name = 'androidx_interpolator__interpolator',
        actual = ':androidx_interpolator__interpolator__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.interpolator:interpolator:1.0.0
    aar_import_impl(name = 'androidx_interpolator__interpolator__1_0_0',
        aar = '@androidx_interpolator__interpolator__1_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    native.alias(name = 'androidx_legacy__legacy_support_core_ui',
        actual = ':androidx_legacy__legacy_support_core_ui__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.legacy:legacy-support-core-ui:1.0.0
    aar_import_impl(name = 'androidx_legacy__legacy_support_core_ui__1_0_0',
        aar = '@androidx_legacy__legacy_support_core_ui__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_asynclayoutinflater__asynclayoutinflater',
            ':androidx_coordinatorlayout__coordinatorlayout',
            ':androidx_core__core',
            ':androidx_cursoradapter__cursoradapter',
            ':androidx_customview__customview',
            ':androidx_drawerlayout__drawerlayout',
            ':androidx_interpolator__interpolator',
            ':androidx_legacy__legacy_support_core_utils',
            ':androidx_slidingpanelayout__slidingpanelayout',
            ':androidx_swiperefreshlayout__swiperefreshlayout',
            ':androidx_viewpager__viewpager',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_asynclayoutinflater__asynclayoutinflater',
            ':androidx_coordinatorlayout__coordinatorlayout',
            ':androidx_core__core',
            ':androidx_cursoradapter__cursoradapter',
            ':androidx_customview__customview',
            ':androidx_drawerlayout__drawerlayout',
            ':androidx_interpolator__interpolator',
            ':androidx_legacy__legacy_support_core_utils',
            ':androidx_slidingpanelayout__slidingpanelayout',
            ':androidx_swiperefreshlayout__swiperefreshlayout',
            ':androidx_viewpager__viewpager',
        ],
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    native.alias(name = 'androidx_legacy__legacy_support_core_utils',
        actual = ':androidx_legacy__legacy_support_core_utils__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.legacy:legacy-support-core-utils:1.0.0
    aar_import_impl(name = 'androidx_legacy__legacy_support_core_utils__1_0_0',
        aar = '@androidx_legacy__legacy_support_core_utils__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_documentfile__documentfile',
            ':androidx_loader__loader',
            ':androidx_localbroadcastmanager__localbroadcastmanager',
            ':androidx_print__print',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_documentfile__documentfile',
            ':androidx_loader__loader',
            ':androidx_localbroadcastmanager__localbroadcastmanager',
            ':androidx_print__print',
        ],
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    native.alias(name = 'androidx_lifecycle__lifecycle_common',
        actual = ':androidx_lifecycle__lifecycle_common__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.lifecycle:lifecycle-common:2.0.0
    java_import_impl(name = 'androidx_lifecycle__lifecycle_common__2_0_0',
        jars = ['@androidx_lifecycle__lifecycle_common__2_0_0//file'],
        tags = ['maven_coordinates=androidx.lifecycle:lifecycle-common:2.0.0'],
        licenses = ['notice'],
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
        runtime_deps = [],
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    native.alias(name = 'androidx_lifecycle__lifecycle_livedata_core',
        actual = ':androidx_lifecycle__lifecycle_livedata_core__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.lifecycle:lifecycle-livedata-core:2.0.0
    aar_import_impl(name = 'androidx_lifecycle__lifecycle_livedata_core__2_0_0',
        aar = '@androidx_lifecycle__lifecycle_livedata_core__2_0_0//file',
        deps = [
            ':androidx_arch_core__core_common',
            ':androidx_arch_core__core_runtime',
            ':androidx_lifecycle__lifecycle_common',
        ],
        exports = [
            ':androidx_arch_core__core_common',
            ':androidx_arch_core__core_runtime',
            ':androidx_lifecycle__lifecycle_common',
        ],
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    native.alias(name = 'androidx_lifecycle__lifecycle_livedata',
        actual = ':androidx_lifecycle__lifecycle_livedata__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.lifecycle:lifecycle-livedata:2.0.0
    aar_import_impl(name = 'androidx_lifecycle__lifecycle_livedata__2_0_0',
        aar = '@androidx_lifecycle__lifecycle_livedata__2_0_0//file',
        deps = [
            ':androidx_arch_core__core_common',
            ':androidx_arch_core__core_runtime',
            ':androidx_lifecycle__lifecycle_livedata_core',
        ],
        exports = [
            ':androidx_arch_core__core_common',
            ':androidx_arch_core__core_runtime',
            ':androidx_lifecycle__lifecycle_livedata_core',
        ],
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    native.alias(name = 'androidx_lifecycle__lifecycle_runtime',
        actual = ':androidx_lifecycle__lifecycle_runtime__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.lifecycle:lifecycle-runtime:2.0.0
    aar_import_impl(name = 'androidx_lifecycle__lifecycle_runtime__2_0_0',
        aar = '@androidx_lifecycle__lifecycle_runtime__2_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_arch_core__core_common',
            ':androidx_lifecycle__lifecycle_common',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_arch_core__core_common',
            ':androidx_lifecycle__lifecycle_common',
        ],
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    native.alias(name = 'androidx_lifecycle__lifecycle_viewmodel',
        actual = ':androidx_lifecycle__lifecycle_viewmodel__2_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.lifecycle:lifecycle-viewmodel:2.0.0
    aar_import_impl(name = 'androidx_lifecycle__lifecycle_viewmodel__2_0_0',
        aar = '@androidx_lifecycle__lifecycle_viewmodel__2_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.loader:loader:1.0.0
    native.alias(name = 'androidx_loader__loader',
        actual = ':androidx_loader__loader__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.loader:loader:1.0.0
    aar_import_impl(name = 'androidx_loader__loader__1_0_0',
        aar = '@androidx_loader__loader__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_livedata',
            ':androidx_lifecycle__lifecycle_viewmodel',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_lifecycle__lifecycle_livedata',
            ':androidx_lifecycle__lifecycle_viewmodel',
        ],
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    native.alias(name = 'androidx_localbroadcastmanager__localbroadcastmanager',
        actual = ':androidx_localbroadcastmanager__localbroadcastmanager__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
    aar_import_impl(name = 'androidx_localbroadcastmanager__localbroadcastmanager__1_0_0',
        aar = '@androidx_localbroadcastmanager__localbroadcastmanager__1_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.print:print:1.0.0
    native.alias(name = 'androidx_print__print',
        actual = ':androidx_print__print__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.print:print:1.0.0
    aar_import_impl(name = 'androidx_print__print__1_0_0',
        aar = '@androidx_print__print__1_0_0//file',
        deps = [':androidx_annotation__annotation'],
        exports = [':androidx_annotation__annotation'],
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    native.alias(name = 'androidx_slidingpanelayout__slidingpanelayout',
        actual = ':androidx_slidingpanelayout__slidingpanelayout__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.slidingpanelayout:slidingpanelayout:1.0.0
    aar_import_impl(name = 'androidx_slidingpanelayout__slidingpanelayout__1_0_0',
        aar = '@androidx_slidingpanelayout__slidingpanelayout__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    native.alias(name = 'androidx_swiperefreshlayout__swiperefreshlayout',
        actual = ':androidx_swiperefreshlayout__swiperefreshlayout__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
    aar_import_impl(name = 'androidx_swiperefreshlayout__swiperefreshlayout__1_0_0',
        aar = '@androidx_swiperefreshlayout__swiperefreshlayout__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_interpolator__interpolator',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_interpolator__interpolator',
        ],
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    native.alias(name = 'androidx_vectordrawable__vectordrawable_animated',
        actual = ':androidx_vectordrawable__vectordrawable_animated__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.vectordrawable:vectordrawable-animated:1.0.0
    aar_import_impl(name = 'androidx_vectordrawable__vectordrawable_animated__1_0_0',
        aar = '@androidx_vectordrawable__vectordrawable_animated__1_0_0//file',
        deps = [
            ':androidx_legacy__legacy_support_core_ui',
            ':androidx_vectordrawable__vectordrawable',
        ],
        exports = [
            ':androidx_legacy__legacy_support_core_ui',
            ':androidx_vectordrawable__vectordrawable',
        ],
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    native.alias(name = 'androidx_vectordrawable__vectordrawable',
        actual = ':androidx_vectordrawable__vectordrawable__1_0_1',
        visibility = ['//visibility:public'],
    )

    # from androidx.vectordrawable:vectordrawable:1.0.1
    aar_import_impl(name = 'androidx_vectordrawable__vectordrawable__1_0_1',
        aar = '@androidx_vectordrawable__vectordrawable__1_0_1//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
        ],
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    native.alias(name = 'androidx_versionedparcelable__versionedparcelable',
        actual = ':androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01',
        visibility = ['//visibility:public'],
    )

    # from androidx.versionedparcelable:versionedparcelable:1.1.0-alpha01
    aar_import_impl(name = 'androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01',
        aar = '@androidx_versionedparcelable__versionedparcelable__1_1_0_alpha01//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_collection__collection',
        ],
    )

    # from androidx.viewpager:viewpager:1.0.0
    native.alias(name = 'androidx_viewpager__viewpager',
        actual = ':androidx_viewpager__viewpager__1_0_0',
        visibility = ['//visibility:public'],
    )

    # from androidx.viewpager:viewpager:1.0.0
    aar_import_impl(name = 'androidx_viewpager__viewpager__1_0_0',
        aar = '@androidx_viewpager__viewpager__1_0_0//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':androidx_core__core',
            ':androidx_customview__customview',
        ],
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    native.alias(name = 'com_github_menny_Chauffeur__lib',
        actual = ':com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406',
        visibility = ['//visibility:public'],
    )

    # from com.github.menny.Chauffeur:lib:90e703256785b7baf9cd37370b62b1d7d3830406
    aar_import_impl(name = 'com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406',
        aar = '@com_github_menny_Chauffeur__lib__90e703256785b7baf9cd37370b62b1d7d3830406//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_appcompat__appcompat',
            ':androidx_fragment__fragment',
        ],
        exports = [':androidx_annotation__annotation'],
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    native.alias(name = 'com_github_menny_Chauffeur__permissions',
        actual = ':com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406',
        visibility = ['//visibility:public'],
    )

    # from com.github.menny.Chauffeur:permissions:90e703256785b7baf9cd37370b62b1d7d3830406
    aar_import_impl(name = 'com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406',
        aar = '@com_github_menny_Chauffeur__permissions__90e703256785b7baf9cd37370b62b1d7d3830406//file',
        deps = [
            ':androidx_annotation__annotation',
            ':androidx_appcompat__appcompat',
            ':androidx_fragment__fragment',
            ':com_github_menny_Chauffeur__lib',
        ],
        exports = [
            ':androidx_annotation__annotation',
            ':com_github_menny_Chauffeur__lib',
        ],
    )


